In [62]:
import pandas as pd
from statsbombpy import sb
from mplsoccer import Pitch

In [63]:
sb.competitions()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-07-15T14:15:54.671676,2024-07-15T14:17:00.877356,2024-07-15T14:17:00.877356,2024-07-15T14:15:54.671676
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-06-13T07:51:02.452825,None,None,2024-06-13T07:51:02.452825
3,16,4,Europe,Champions League,male,False,False,2018/2019,2024-06-12T07:44:38.559714,2021-06-13T16:17:31.694,None,2024-06-12T07:44:38.559714
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
...,...,...,...,...,...,...,...,...,...,...,...,...
69,55,43,Europe,UEFA Euro,male,False,True,2020,2024-04-16T12:44:40.558402,2024-04-16T12:47:18.505110,2024-04-16T12:47:18.505110,2024-04-16T12:44:40.558402
70,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2024-02-12T14:45:05.702250,2021-06-13T16:17:31.694,None,2024-02-12T14:45:05.702250
71,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2024-02-13T13:27:17.178263,2024-02-13T13:30:52.820588,2024-02-13T13:30:52.820588,2024-02-13T13:27:17.178263
72,72,107,International,Women's World Cup,female,False,True,2023,2024-07-14T16:59:48.469596,2024-07-14T17:01:38.887279,2024-07-14T17:01:38.887279,2024-07-14T16:59:48.469596
73,72,30,International,Women's World Cup,female,False,True,2019,2024-02-13T09:41:26.379767,2021-06-13T16:17:31.694,None,2024-02-13T09:41:26.379767

In [64]:
from itscalledsoccer.client import AmericanSoccerAnalysis

asa_client = AmericanSoccerAnalysis()

In [65]:
asa_client.get_teams(leagues="mls")

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))

,team_id,team_name,team_short_name,team_abbreviation,competition
17,0KPqjA456v,San Jose Earthquakes,San Jose,SJE,mls
18,19vQ2095K6,New England Revolution,New England,NER,mls
19,4wM42l4qjB,Chivas USA,Chivas,CHV,mls
20,9z5k7Yg5A3,Philadelphia Union,Philadelphia,PHI,mls
21,a2lqR4JMr0,Real Salt Lake,Salt Lake,RSL,mls
22,a2lqRX2Mr0,New York Red Bulls,New York,NYRB,mls
23,APk5LGOMOW,CF Montréal,Montréal,MTL,mls
24,EKXMeX3Q64,D.C. United,D.C. United,DCU,mls
25,eVq3ya6MWO,Los Angeles FC,Los Angeles FC,LAFC,mls
26,gpMOLwl5zy,Austin FC,Austin,ATX,mls
27,jYQJ19EqGR,Seattle Sounders FC,Seattle,SEA,mls
28,jYQJ8EW5GR,Orlando City SC,Orlando City,ORL,mls
29,kaDQ0wRqEv,LA Galaxy,LA Galaxy,LAG,mls
30,KAqBN0Vqbg,Atlanta United FC,Atlanta,ATL,mls
31,kRQabn8MKZ,Toronto FC,Toronto,TOR,mls
32,kRQand1MKZ,Minnesota United FC,Minnesota,MIN,mls
33,lgpMOvnQzy,Vancouver Whitecaps FC,Vancouver,VAN,mls
34,mKAqBBmqbg,FC Dallas,Dallas,FCD,mls
35,mvzqoLZQap,Columbus Crew,Columbus,CLB,mls
36,NPqxKXZ59d,Charlotte FC,Charlotte,CLT,mls
37,NWMWlBK5lz,FC Cincinnati,Cincinnati,CIN,mls
38,pzeQZ6xQKw,Colorado Rapids,Colorado,COL,mls
39,Vj58weDM8n,New York City FC,New York City,NYC,mls
40,vzqoOgNqap,Nashville SC,Nashville,NSH,mls
41,WBLMvYAQxe,Portland Timbers FC,Portland,POR,mls
42,wvq9B9wQWn,St. Louis City SC,St. Louis,STL,mls
43,X0Oq66zq6D,Chicago Fire FC,Chicago,CHI,mls
44,YgOMngl5wN,Houston Dynamo FC,Houston,HOU,mls
45,Z2vQ1xlqrA,Sporting Kansas City,Kansas City,SKC,mls
46,zeQZkL1MKw,Inter Miami CF,Miami,MIA,mls

In [66]:
df_austin_fc = asa_client.get_games(team_names="Austin FC", seasons="2024")
print(df_austin_fc)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))

       game_id            date_time_utc  home_score  away_score home_team_id  \
0   0x5gzY9PM7  2024-07-21 00:30:00 UTC           2           2   gpMOLwl5zy
1   KAqBoZ3JQb  2024-07-18 00:30:00 UTC           3           1   mKAqBBmqbg
2   xW5pJNWlQg  2024-07-14 00:30:00 UTC           0           1   gpMOLwl5zy
3   gjMNr2VvMK  2024-07-07 01:55:00 UTC           2           1   gpMOLwl5zy
4   ljqEkvWEMx  2024-06-30 00:30:00 UTC           2           0   Z2vQ1xlqrA
5   ljqEkvZzMx  2024-06-23 00:30:00 UTC           0           1   kRQand1MKZ
6   vzqozyAj5a  2024-06-20 00:30:00 UTC           1           1   gpMOLwl5zy
7   Oa5w6NpjM1  2024-06-16 01:30:00 UTC           2           0   pzeQZ6xQKw
8   XVqK7rPOq0  2024-06-02 01:30:00 UTC           5           1   a2lqR4JMr0
9   2vQ11JzKQr  2024-05-30 00:30:00 UTC           0           2   gpMOLwl5zy
10  315VzAa959  2024-05-26 02:30:00 UTC           1           1   0KPqjA456v
11  vzqozylk5a  2024-05-19 00:30:00 UTC           3           2   gpMOLwl5zy
12  9YqdzyGLMv  2024-05-16 00:30:00 UTC           1           0   gpMOLwl5zy
13  wvq9wO8wMW  2024-05-12 00:30:00 UTC           2           1   mKAqBBmqbg
14  eVq3l3DDQW  2024-05-05 02:30:00 UTC           0           0   lgpMOvnQzy
15  e7MzoN295r  2024-04-27 17:45:00 UTC           2           0   gpMOLwl5zy
16  KXMezynX56  2024-04-21 00:30:00 UTC           0           1   YgOMngl5wN
17  raMyn0xk5d  2024-04-14 20:45:00 UTC           1           0   wvq9B9wQWn
18  ljqEkvbAMx  2024-04-07 00:30:00 UTC           4           3   gpMOLwl5zy
19  KXMezybX56  2024-03-31 00:30:00 UTC           2           1   gpMOLwl5zy
20  2lqReA8A5r  2024-03-23 23:30:00 UTC           2           0   jYQJ8EW5GR
21  2lqReA825r  2024-03-17 00:30:00 UTC           2           2   gpMOLwl5zy
22  jYQJyrrWqG  2024-03-10 01:30:00 UTC           2           2   gpMOLwl5zy
23  4JMAnzz75K  2024-03-03 03:30:00 UTC           0           0   jYQJ19EqGR
24  EGMP8AArMa  2024-02-25 01:30:00 UTC           1           2   gpMOLwl5zy

   away_team_id  referee_id  stadium_id home_manager_id away_manager_id  \
0    NPqxKXZ59d  4JMAYlPMKg  jYQJZDDQGR      0Oq6mNP56D      wvq9NPNQWn
1    gpMOLwl5zy  gjMNk4v5Kp  eVq3alGMWO      zeQZyzZqKw      0Oq6mNP56D
2    jYQJ19EqGR  9z5kJ7gMA3  jYQJZDDQGR      0Oq6mNP56D      odMXxreMYL
3    Vj58weDM8n  kRQa9k8QKZ  jYQJZDDQGR      0Oq6mNP56D      gpMOPN75zy
4    gpMOLwl5zy  xW5pE3Yqg1  NPqxy6XQ9d      N6MmpyLQEG      0Oq6mNP56D
5    gpMOLwl5zy  Pk5LRpDQOW  odMXGRrQYL      KAqBEaW5bg      0Oq6mNP56D
6    eVq3ya6MWO  EGMPLlxMaY  jYQJZDDQGR      0Oq6mNP56D      NWMWxKe5lz
7    gpMOLwl5zy  ljqEymNqx0  9z5ka6gQA3      vzqo2dv5ap      0Oq6mNP56D
8    gpMOLwl5zy  e7MzjxJMr0  e7MzlRjqr0      4wM4vOAqjB      0Oq6mNP56D
9    WBLMvYAQxe  2lqRymD5r0  jYQJZDDQGR      0Oq6mNP56D      gpMOYJ7qzy
10   gpMOLwl5zy  jYQJnoVQGR  Vj58W84M8n      eV5DNVJQKn      0Oq6mNP56D
11   Z2vQ1xlqrA  Vj58OwwM8n  jYQJZDDQGR      0Oq6mNP56D      N6MmpyLQEG
12   YgOMngl5wN  e7MzPKXqr0  jYQJZDDQGR      0Oq6mNP56D      vzqoAjJMap
13   gpMOLwl5zy  9z5kJ7gMA3  eVq3alGMWO      KAqBwv7Qbg      0Oq6mNP56D
14   gpMOLwl5zy  0Oq6vG2q6D  ljqEDnO5x0      Pk5LWONMOW      0Oq6mNP56D
15   kaDQ0wRqEv  2lqRymD5r0  jYQJZDDQGR      0Oq6mNP56D      Xj5Yx60Mbd
16   gpMOLwl5zy  ljqExYw5x0  0x5g6ojM7O      vzqoAjJMap      0Oq6mNP56D
17   gpMOLwl5zy  EGMPLlxMaY  4wM4ez45jB      zeQZVw1QKw      0Oq6mNP56D
18   0KPqjA456v  2lqRG1WQr0  jYQJZDDQGR      0Oq6mNP56D      eV5DNVJQKn
19   mKAqBBmqbg  9vQ2mPaqK6  jYQJZDDQGR      0Oq6mNP56D      KAqBwv7Qbg
20   gpMOLwl5zy  EGMPEpj5aY  vzqoJrj5ap      gjMNk8v5Kp      0Oq6mNP56D
21   9z5k7Yg5A3  0x5ggRZ57O  jYQJZDDQGR      0Oq6mNP56D      0Oq6vPrq6D
22   wvq9B9wQWn  0x5gZv7M7O  jYQJZDDQGR      0Oq6mNP56D      zeQZVw1QKw
23   gpMOLwl5zy  315Vv0X59x  9Yqda07QvJ      odMXxreMYL      0Oq6mNP56D
24   kRQand1MKZ  7VqG8p3QvW  jYQJZDDQGR      0Oq6mNP56D      e7MzXrOqr0

    expanded_minutes  season_name  matchday  attendance  knockout_game  \
0                101         2024        27           0          False
1                106         2024        26           0          False
2                 98         2024        25       20738          False
3                107         2024        24       20738          False
4                 99         2024        22       18722          False
5                100         2024        21       19746          False
6                 99         2024        20       20738          False
7                 99         2024        19       17433          False
8                105         2024        17       21078          False
9                104         2024        16       20738          False
10                95         2024        15       13744          False
11               104         2024        14       20738          False
12                98         2024        13       20738          False
13               101         2024        12       19069          False
14               104         2024        11       32465          False
15                99         2024        10       20738          False
16               100         2024         9       20115          False
17               103         2024         8       22423          False
18               110         2024         7       20738          False
19               102         2024         6       20738          False
20                98         2024         5       20985          False
21               105         2024         4       20738          False
22                99         2024         3       20738          False
23               103         2024         2       30067          False
24                99         2024         1       20738          False

           last_updated_utc
0   2024-07-21 02:46:19 UTC
1   2024-07-19 12:12:20 UTC
2   2024-07-16 05:40:05 UTC
3   2024-07-10 05:14:50 UTC
4   2024-07-02 11:12:20 UTC
5   2024-06-26 08:01:34 UTC
6   2024-06-22 23:05:47 UTC
7   2024-06-18 04:49:32 UTC
8   2024-06-04 09:54:25 UTC
9   2024-06-01 10:11:26 UTC
10  2024-05-29 10:57:30 UTC
11  2024-05-21 22:43:52 UTC
12  2024-05-18 06:32:24 UTC
13  2024-05-14 06:25:20 UTC
14  2024-05-07 23:06:07 UTC
15  2024-04-30 01:45:28 UTC
16  2024-04-23 23:01:21 UTC
17  2024-04-19 13:27:51 UTC
18  2024-04-10 09:31:53 UTC
19  2024-04-03 12:03:44 UTC
20  2024-03-26 06:26:20 UTC
21  2024-03-22 11:18:56 UTC
22  2024-03-12 19:21:39 UTC
23  2024-03-05 20:11:17 UTC
24  2024-02-28 06:26:34 UTC

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))

In [67]:
asa_client.get_game_xgoals(game_id="0x5gzY9PM7")

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))

,game_id,date_time_utc,home_team_id,home_goals,home_team_xgoals,home_player_xgoals,away_team_id,away_goals,away_team_xgoals,away_player_xgoals,goal_difference,team_xgoal_difference,player_xgoal_difference,final_score_difference,home_xpoints,away_xpoints
0,0x5gzY9PM7,2024-07-21 00:30:00 UTC,gpMOLwl5zy,2,2.4055,2.4055,NPqxKXZ59d,2,2.4263,2.4263,0,-0.0208,-0.0208,0,1.442,1.322

In [68]:
players = asa_client.get_players()
print(players)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))

        player_id             player_name  birth_date nationality  \
0      0Oq6243Pq6             Lena Silano  2000-02-28         USA
1      0Oq62ob2q6            Heather Hinz         NaN         USA
2      0Oq632XPQ6         Jenna Hellstrom  1995-04-02      Canada
3      0Oq63967Q6            Julia Dorsey  2000-08-08         USA
4      0Oq63d8XQ6           Maddie Huster  1996-07-05         USA
...           ...                     ...         ...         ...
10730  zeQZXojN5K        Anthony Alaouieh  2006-07-24         USA
10731  zeQZXXm15K              Jake Davis  2002-01-03         USA
10732  zeQZXyBx5K          Maclovio Swett  2004-05-26         USA
10733  zeQZXZ9Z5K           Elijah Amadin  1999-06-16         USA
10734  zeQZXzwD5K  Sebastian Joffre Soliz  1999-08-21     Bolivia

      primary_broad_position primary_general_position  \
0                         FW                       ST
1                        NaN                      NaN
2                         DF                       FB
3                        NaN                      NaN
4                        NaN                      NaN
...                      ...                      ...
10730                     FW                        W
10731                     MF                       CM
10732                     MF                        W
10733                     DF                       FB
10734                     DF                       FB

      secondary_broad_position secondary_general_position   season_name  \
0                           MF                          W  [2023, 2024]
1                          NaN                        NaN            {}
2                          NaN                        NaN          2020
3                          NaN                        NaN            {}
4                          NaN                        NaN            {}
...                        ...                        ...           ...
10730                      NaN                        NaN  [2023, 2024]
10731                      NaN                        NaN  [2022, 2023]
10732                       FW                          W          2022
10733                      NaN                        NaN          2023
10734                       MF                          W          2024

       height_ft  height_in  weight_lb competition
0            NaN        NaN        NaN        nwsl
1            NaN        NaN        NaN        nwsl
2            5.0        6.0        NaN        nwsl
3            NaN        NaN        NaN        nwsl
4            5.0        4.0        NaN        nwsl
...          ...        ...        ...         ...
10730        NaN        NaN        NaN       mlsnp
10731        5.0       10.0      150.0       mlsnp
10732        NaN        NaN        NaN       mlsnp
10733        6.0        0.0        NaN       mlsnp
10734        5.0        8.0      150.0       mlsnp

[10735 rows x 13 columns]

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))

In [69]:
austin_players_goals_added = asa_client.get_player_goals_added(team_ids="gpMOLwl5zy")
print(austin_players_goals_added)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))

     player_id     team_id general_position  minutes_played  \
0   0Oq67EgQ6D  gpMOLwl5zy               CB            1938
1   0Oq6lLZgM6  gpMOLwl5zy               ST            3605
2   2lqRJeA4qr  gpMOLwl5zy                W              12
3   2vQ1dVlLqr  gpMOLwl5zy               DM              32
4   2vQ1NO0OMr  gpMOLwl5zy                W            1876
5   315V7zn7q9  gpMOLwl5zy               CM             353
6   315VXPJEQ9  gpMOLwl5zy               CB            9784
7   4JMAaoa7MK  gpMOLwl5zy               FB            3047
8   4JMAolz1qK  gpMOLwl5zy               DM            8713
9   4wM4J8bNqj  gpMOLwl5zy                W            4729
10  7vQ7BardqD  gpMOLwl5zy               DM              57
11  7VqGjBpz5v  gpMOLwl5zy                W            1343
12  7VqGjPKj5v  gpMOLwl5zy               CB            2371
13  9vQ2dZE15K  gpMOLwl5zy               ST             449
14  9YqdogzE5v  gpMOLwl5zy                W            1624
15  BLMvzPNlMx  gpMOLwl5zy                W            2860
16  EGMPlpRxMa  gpMOLwl5zy               ST            2721
17  eV5DzmNmQK  gpMOLwl5zy               CB             864
18  eV5Dzr7EQK  gpMOLwl5zy                W             290
19  eVq3alzDMW  gpMOLwl5zy               FB              40
20  eVq3xk1VQW  gpMOLwl5zy               DM             752
21  gOMn66nAMw  gpMOLwl5zy               DM           10923
22  gOMnR6e6Mw  gpMOLwl5zy               FB            7873
23  gpMOaDWrqz  gpMOLwl5zy               CM            2415
24  gpMOz1KyQz  gpMOLwl5zy               ST            1653
25  gpMOzKV7Qz  gpMOLwl5zy                W             408
26  KXMekOprq6  gpMOLwl5zy               AM            9271
27  KXMeOaaPq6  gpMOLwl5zy                W            3710
28  ljqE2ekNQx  gpMOLwl5zy               FB            4642
29  ljqE2PwVQx  gpMOLwl5zy                W             293
30  ljqEjLaEQx  gpMOLwl5zy                W            7128
31  N6MmepZxME  gpMOLwl5zy               DM            3418
32  NPqxm7JXQ9  gpMOLwl5zy               FB              94
33  NWMWVR6jQl  gpMOLwl5zy               CB            1962
34  NWMWXylK5l  gpMOLwl5zy               CB            1123
35  Oa5wVLWAM1  gpMOLwl5zy               FB             995
36  Oa5wVojBM1  gpMOLwl5zy               DM              70
37  Oa5wVwxXM1  gpMOLwl5zy               FB             275
38  Oa5wVzD9M1  gpMOLwl5zy               CB             391
39  p6qb0L4M0G  gpMOLwl5zy               CB            3356
40  p6qbenoB50  gpMOLwl5zy                W            4918
41  raMyA6KRMd  gpMOLwl5zy               FB            9307
42  raMyAn8AMd  gpMOLwl5zy               CB            2885
43  wvq9bOBQWn  gpMOLwl5zy               DM             976
44  wvq9epE3qW  gpMOLwl5zy               ST             435
45  Xj5Y6AlAqb  gpMOLwl5zy               ST             246
46  Xj5Y9bmX5b  gpMOLwl5zy               ST            1413
47  Xj5Y9eBx5b  gpMOLwl5zy                W              62
48  xW5pynPBqg  gpMOLwl5zy               FB            1758
49  zeQZzPgQKw  gpMOLwl5zy               ST             809

                                                 data
0   [{'action_type': 'Dribbling', 'goals_added_raw...
1   [{'action_type': 'Dribbling', 'goals_added_raw...
2   [{'action_type': 'Dribbling', 'goals_added_raw...
3   [{'action_type': 'Dribbling', 'goals_added_raw...
4   [{'action_type': 'Dribbling', 'goals_added_raw...
5   [{'action_type': 'Dribbling', 'goals_added_raw...
6   [{'action_type': 'Dribbling', 'goals_added_raw...
7   [{'action_type': 'Dribbling', 'goals_added_raw...
8   [{'action_type': 'Dribbling', 'goals_added_raw...
9   [{'action_type': 'Dribbling', 'goals_added_raw...
10  [{'action_type': 'Dribbling', 'goals_added_raw...
11  [{'action_type': 'Dribbling', 'goals_added_raw...
12  [{'action_type': 'Dribbling', 'goals_added_raw...
13  [{'action_type': 'Dribbling', 'goals_added_raw...
14  [{'action_type': 'Dribbling', 'goals_added_raw...
15  [{'action_type': 'Dribbling', 'goals_added_raw...
16  [{'action_type': 'Dribbling', 'goals_added_raw...
17  [{'action_type': 'Dribbling', 'goals_added_raw...
18  [{'action_type': 'Dribbling', 'goals_added_raw...
19  [{'action_type': 'Dribbling', 'goals_added_raw...
20  [{'action_type': 'Dribbling', 'goals_added_raw...
21  [{'action_type': 'Dribbling', 'goals_added_raw...
22  [{'action_type': 'Dribbling', 'goals_added_raw...
23  [{'action_type': 'Dribbling', 'goals_added_raw...
24  [{'action_type': 'Dribbling', 'goals_added_raw...
25  [{'action_type': 'Dribbling', 'goals_added_raw...
26  [{'action_type': 'Dribbling', 'goals_added_raw...
27  [{'action_type': 'Dribbling', 'goals_added_raw...
28  [{'action_type': 'Dribbling', 'goals_added_raw...
29  [{'action_type': 'Dribbling', 'goals_added_raw...
30  [{'action_type': 'Dribbling', 'goals_added_raw...
31  [{'action_type': 'Dribbling', 'goals_added_raw...
32  [{'action_type': 'Dribbling', 'goals_added_raw...
33  [{'action_type': 'Dribbling', 'goals_added_raw...
34  [{'action_type': 'Dribbling', 'goals_added_raw...
35  [{'action_type': 'Dribbling', 'goals_added_raw...
36  [{'action_type': 'Dribbling', 'goals_added_raw...
37  [{'action_type': 'Dribbling', 'goals_added_raw...
38  [{'action_type': 'Dribbling', 'goals_added_raw...
39  [{'action_type': 'Dribbling', 'goals_added_raw...
40  [{'action_type': 'Dribbling', 'goals_added_raw...
41  [{'action_type': 'Dribbling', 'goals_added_raw...
42  [{'action_type': 'Dribbling', 'goals_added_raw...
43  [{'action_type': 'Dribbling', 'goals_added_raw...
44  [{'action_type': 'Dribbling', 'goals_added_raw...
45  [{'action_type': 'Dribbling', 'goals_added_raw...
46  [{'action_type': 'Dribbling', 'goals_added_raw...
47  [{'action_type': 'Dribbling', 'goals_added_raw...
48  [{'action_type': 'Dribbling', 'goals_added_raw...
49  [{'action_type': 'Dribbling', 'goals_added_raw...

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))

In [70]:
austin_player_ids = austin_players_goals_added['player_id']
print(austin_player_ids)

0     0Oq67EgQ6D
1     0Oq6lLZgM6
2     2lqRJeA4qr
3     2vQ1dVlLqr
4     2vQ1NO0OMr
5     315V7zn7q9
6     315VXPJEQ9
7     4JMAaoa7MK
8     4JMAolz1qK
9     4wM4J8bNqj
10    7vQ7BardqD
11    7VqGjBpz5v
12    7VqGjPKj5v
13    9vQ2dZE15K
14    9YqdogzE5v
15    BLMvzPNlMx
16    EGMPlpRxMa
17    eV5DzmNmQK
18    eV5Dzr7EQK
19    eVq3alzDMW
20    eVq3xk1VQW
21    gOMn66nAMw
22    gOMnR6e6Mw
23    gpMOaDWrqz
24    gpMOz1KyQz
25    gpMOzKV7Qz
26    KXMekOprq6
27    KXMeOaaPq6
28    ljqE2ekNQx
29    ljqE2PwVQx
30    ljqEjLaEQx
31    N6MmepZxME
32    NPqxm7JXQ9
33    NWMWVR6jQl
34    NWMWXylK5l
35    Oa5wVLWAM1
36    Oa5wVojBM1
37    Oa5wVwxXM1
38    Oa5wVzD9M1
39    p6qb0L4M0G
40    p6qbenoB50
41    raMyA6KRMd
42    raMyAn8AMd
43    wvq9bOBQWn
44    wvq9epE3qW
45    Xj5Y6AlAqb
46    Xj5Y9bmX5b
47    Xj5Y9eBx5b
48    xW5pynPBqg
49    zeQZzPgQKw
Name: player_id, dtype: object

In [73]:
# Loop through each player ID to fetch data
for player_id in austin_player_ids:
    # Fetch player data
    player_data = asa_client.get_players(ids=player_id)

    print(player_data)

      player_id  player_name  birth_date nationality primary_broad_position  \
918  0Oq67EgQ6D  Matt Besler  1987-02-11         USA                     DF

    primary_general_position secondary_broad_position  \
918                       CB                      NaN

    secondary_general_position  \
918                        NaN

                                           season_name  height_ft  height_in  \
918  [2013, 2014, 2015, 2016, 2017, 2018, 2019, 202...        6.0        0.0

     weight_lb competition
918      172.0         mls
      player_id         player_name  birth_date nationality  \
941  0Oq6lLZgM6  Maximiliano Urruti  1991-02-22   Argentina

    primary_broad_position primary_general_position secondary_broad_position  \
941                     FW                       ST                      NaN

    secondary_general_position  \
941                        NaN

                                           season_name  height_ft  height_in  \
941  [2013, 2014, 2015, 2016, 2017, 2018, 2019, 202...        6.0        0.0

     weight_lb competition
941      165.0         mls
       player_id       player_name  birth_date nationality  \
1076  2lqRJeA4qr  Bryant Farkarlun  2001-07-14     Liberia
8858  2lqRJeA4qr  Bryant Farkarlun  2001-07-14     Liberia

     primary_broad_position primary_general_position secondary_broad_position  \
1076                     MF                        W                      NaN
8858                     FW                        W                      NaN

     secondary_general_position season_name  height_ft  height_in  weight_lb  \
1076                        NaN        2024        NaN        NaN        NaN
8858                        NaN        2024        NaN        NaN        NaN

     competition
1076         mls
8858       mlsnp
       player_id     player_name  birth_date nationality  \
1166  2vQ1dVlLqr  Alonso Jiménez  2001-08-20      Mexico
8921  2vQ1dVlLqr  Alonso Jiménez  2001-08-20      Mexico

     primary_broad_position primary_general_position secondary_broad_position  \
1166                     MF                       DM                      NaN
8921                     MF                       DM                      NaN

     secondary_general_position   season_name  height_ft  height_in  \
1166                        NaN          2024        NaN        NaN
8921                        NaN  [2023, 2024]        NaN        NaN

      weight_lb competition
1166        NaN         mls
8921        NaN       mlsnp
       player_id   player_name  birth_date nationality primary_broad_position  \
1193  2vQ1NO0OMr  Jáder Obrian  1995-05-18    Colombia                     MF

     primary_general_position secondary_broad_position  \
1193                        W                      NaN

     secondary_general_position               season_name  height_ft  \
1193                        NaN  [2021, 2022, 2023, 2024]        5.0

      height_in  weight_lb competition
1193        6.0      137.0         mls
       player_id      player_name  birth_date nationality  \
1205  315V7zn7q9  Sofiane Djeffal  1999-04-19      France
4203  315V7zn7q9  Sofiane Djeffal  1999-04-19      France

     primary_broad_position primary_general_position secondary_broad_position  \
1205                     MF                       CM                      NaN
4203                     MF                       CM                      NaN

     secondary_general_position   season_name  height_ft  height_in  \
1205                         DM  [2022, 2023]        NaN        NaN
4203                        NaN          2024        NaN        NaN

      weight_lb competition
1205        NaN         mls
4203        NaN        uslc
       player_id     player_name  birth_date nationality  \
1253  315VXPJEQ9  Julio Cascante  1993-10-03  Costa Rica
4263  315VXPJEQ9  Julio Cascante  1993-10-03  Costa Rica

     primary_broad_position primary_general_position secondary_broad_position  \
1253                     DF                       CB                      NaN
4263                     DF                       CB                      NaN

     secondary_general_position                                 season_name  \
1253                        NaN  [2018, 2019, 2020, 2021, 2022, 2023, 2024]
4263                        NaN                                        2018

      height_ft  height_in  weight_lb competition
1253        6.0        1.0        NaN         mls
4263        6.0        1.0        NaN        uslc
       player_id     player_name  birth_date nationality  \
1286  4JMAaoa7MK  Héctor Jiménez  1988-11-03         USA

     primary_broad_position primary_general_position secondary_broad_position  \
1286                     DF                       FB                      NaN

     secondary_general_position  \
1286                        NaN

                                            season_name  height_ft  height_in  \
1286  [2013, 2014, 2015, 2016, 2017, 2018, 2019, 202...        5.0        9.0

      weight_lb competition
1286      141.0         mls
       player_id         player_name  birth_date nationality  \
1307  4JMAolz1qK  Daniel Pereira Gil  2000-07-14   Venezuela

     primary_broad_position primary_general_position secondary_broad_position  \
1307                     MF                       DM                      NaN

     secondary_general_position               season_name  height_ft  \
1307                         CM  [2021, 2022, 2023, 2024]        5.0

      height_in  weight_lb competition
1307        9.0        NaN         mls
       player_id player_name  birth_date nationality primary_broad_position  \
1354  4wM4J8bNqj  Owen Wolff  2004-12-30         USA                     MF
4383  4wM4J8bNqj  Owen Wolff  2004-12-30         USA                    NaN

     primary_general_position secondary_broad_position  \
1354                       DM                      NaN
4383                      NaN                      NaN

     secondary_general_position               season_name  height_ft  \
1354                          W  [2021, 2022, 2023, 2024]        5.0
4383                        NaN                        {}        5.0

      height_in  weight_lb competition
1354        9.0      146.0         mls
4383        9.0      146.0        uslc
       player_id        player_name  birth_date nationality  \
1396  7vQ7BardqD  Frederik Kleemann  1999-03-19         USA
4432  7vQ7BardqD  Frederik Kleemann  1999-03-19         USA

     primary_broad_position primary_general_position secondary_broad_position  \
1396                     MF                       DM                       DF
4432                     DF                       CB                      NaN

     secondary_general_position               season_name  height_ft  \
1396                         CB                      2021        6.0
4432                        NaN  [2021, 2022, 2023, 2024]        6.0

      height_in  weight_lb competition
1396        4.0        NaN         mls
4432        4.0        NaN        uslc
       player_id   player_name  birth_date nationality primary_broad_position  \
1489  7VqGjBpz5v  Jared Stroud  1996-07-10         USA                     MF
4520  7VqGjBpz5v  Jared Stroud  1996-07-10         USA                     MF

     primary_general_position secondary_broad_position  \
1489                        W                      NaN
4520                        W                      NaN

     secondary_general_position                     season_name  height_ft  \
1489                        NaN  [2020, 2021, 2022, 2023, 2024]        5.0
4520                        NaN              [2018, 2019, 2020]        5.0

      height_in  weight_lb competition
1489       10.0      154.0         mls
4520       10.0      154.0        uslc
       player_id    player_name  birth_date nationality  \
1498  7VqGjPKj5v  Jhohan Romaña  1998-09-13    Colombia

     primary_broad_position primary_general_position secondary_broad_position  \
1498                     DF                       CB                      NaN

     secondary_general_position   season_name  height_ft  height_in  \
1498                        NaN  [2021, 2022]        6.0        1.0

      weight_lb competition
1498      174.0         mls
       player_id player_name  birth_date nationality primary_broad_position  \
1570  9vQ2dZE15K  Will Bruin  1989-10-24         USA                     FW
4607  9vQ2dZE15K  Will Bruin  1989-10-24         USA                     FW

     primary_general_position secondary_broad_position  \
1570                       ST                      NaN
4607                       ST                      NaN

     secondary_general_position  \
1570                        NaN
4607                        NaN

                                            season_name  height_ft  height_in  \
1570  [2013, 2014, 2015, 2016, 2017, 2018, 2019, 202...        6.0        2.0
4607                                               2019        6.0        2.0

      weight_lb competition
1570      196.0         mls
4607      196.0        uslc
       player_id   player_name  birth_date nationality primary_broad_position  \
1634  9YqdogzE5v  Rodney Redes  2000-02-22    Paraguay                     MF

     primary_general_position secondary_broad_position  \
1634                        W                      NaN

     secondary_general_position         season_name  height_ft  height_in  \
1634                        NaN  [2021, 2022, 2023]        NaN        NaN

      weight_lb competition
1634        NaN         mls
       player_id        player_name  birth_date nationality  \
1884  BLMvzPNlMx  Cecilio Domínguez  1994-08-11    Paraguay

     primary_broad_position primary_general_position secondary_broad_position  \
1884                     FW                       ST                       MF

     secondary_general_position   season_name  height_ft  height_in  \
1884                          W  [2021, 2022]        5.0       10.0

      weight_lb competition
1884      161.0         mls
       player_id   player_name  birth_date nationality primary_broad_position  \
1950  EGMPlpRxMa  Gyasi Zardes  1991-09-02         USA                     FW
9436  EGMPlpRxMa  Gyasi Zardes  1991-09-02         USA                     FW

     primary_general_position secondary_broad_position  \
1950                       ST                      NaN
9436                       ST                      NaN

     secondary_general_position  \
1950                        NaN
9436                        NaN

                                            season_name  height_ft  height_in  \
1950  [2013, 2014, 2015, 2016, 2017, 2018, 2019, 202...        6.0        2.0
9436                                               2022        6.0        2.0

      weight_lb competition
1950      176.0         mls
9436      176.0       mlsnp
       player_id  player_name  birth_date nationality primary_broad_position  \
2054  eV5DzmNmQK  Kipp Keller  2000-07-14         USA                     DF
9517  eV5DzmNmQK  Kipp Keller  2000-07-14         USA                     DF

     primary_general_position secondary_broad_position  \
2054                       CB                      NaN
9517                       CB                      NaN

     secondary_general_position         season_name  height_ft  height_in  \
2054                        NaN  [2022, 2023, 2024]        6.0        1.0
9517                        NaN        [2023, 2024]        6.0        1.0

      weight_lb competition
2054      181.0         mls
9517      181.0       mlsnp
       player_id    player_name  birth_date nationality  \
2055  eV5Dzr7EQK  Calvin Fodrey  2004-02-10         USA
5176  eV5Dzr7EQK  Calvin Fodrey  2004-02-10         USA
9520  eV5Dzr7EQK  Calvin Fodrey  2004-02-10         USA

     primary_broad_position primary_general_position secondary_broad_position  \
2055                     MF                        W                      NaN
5176                     DF                       FB                      NaN
9520                     MF                        W                       FW

     secondary_general_position   season_name  height_ft  height_in  \
2055                        NaN  [2023, 2024]        6.0        2.0
5176                        NaN  [2021, 2022]        6.0        2.0
9520                          W  [2023, 2024]        6.0        2.0

      weight_lb competition
2055      159.0         mls
5176      159.0        uslc
9520      159.0       mlsnp
       player_id    player_name  birth_date nationality  \
2069  eVq3alzDMW  Mikkel Desler  1995-02-19     Denmark

     primary_broad_position primary_general_position secondary_broad_position  \
2069                     DF                       FB                      NaN

     secondary_general_position season_name  height_ft  height_in  weight_lb  \
2069                        NaN        2024        6.0        0.0      161.0

     competition
2069         mls
       player_id          player_name  birth_date nationality  \
2125  eVq3xk1VQW  Sebastian Berhalter  2001-05-10         USA
9544  eVq3xk1VQW  Sebastian Berhalter  2001-05-10         USA

     primary_broad_position primary_general_position secondary_broad_position  \
2125                     MF                       CM                      NaN
9544                     MF                       CM                      NaN

     secondary_general_position                     season_name  height_ft  \
2125                         DM  [2020, 2021, 2022, 2023, 2024]        5.0
9544                        NaN                            2022        5.0

      height_in  weight_lb competition
2125        9.0      154.0         mls
9544        9.0      154.0       mlsnp
       player_id     player_name  birth_date nationality  \
2208  gOMn66nAMw  Alexander Ring  1991-04-09     Finland

     primary_broad_position primary_general_position secondary_broad_position  \
2208                     MF                       DM                      NaN

     secondary_general_position  \
2208                        NaN

                                           season_name  height_ft  height_in  \
2208  [2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]        5.0       10.0

      weight_lb competition
2208      161.0         mls
       player_id player_name  birth_date nationality primary_broad_position  \
2271  gOMnR6e6Mw   Nick Lima  1994-11-17         USA                     DF

     primary_general_position secondary_broad_position  \
2271                       FB                      NaN

     secondary_general_position  \
2271                        NaN

                                           season_name  height_ft  height_in  \
2271  [2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]        5.0        9.0

      weight_lb competition
2271      176.0         mls
       player_id       player_name  birth_date nationality  \
2311  gpMOaDWrqz  Tomás Pochettino  1996-02-01   Argentina

     primary_broad_position primary_general_position secondary_broad_position  \
2311                     MF                       CM                      NaN

     secondary_general_position season_name  height_ft  height_in  weight_lb  \
2311                        NaN        2021        5.0       10.0      165.0

     competition
2311         mls
       player_id  player_name  birth_date nationality primary_broad_position  \
2367  gpMOz1KyQz  Diego Rubio  1993-05-15       Chile                     FW
5538  gpMOz1KyQz  Diego Rubio  1993-05-15       Chile                     FW
9722  gpMOz1KyQz  Diego Rubio  1993-05-15       Chile                     MF

     primary_general_position secondary_broad_position  \
2367                       ST                      NaN
5538                       ST                      NaN
9722                       AM                      NaN

     secondary_general_position  \
2367                        NaN
5538                        NaN
9722                        NaN

                                            season_name  height_ft  height_in  \
2367  [2016, 2017, 2018, 2019, 2020, 2021, 2022, 202...        5.0       10.0
5538                                       [2017, 2018]        5.0       10.0
9722                                       [2022, 2023]        5.0       10.0

      weight_lb competition
2367      168.0         mls
5538      168.0        uslc
9722      168.0       mlsnp
       player_id    player_name  birth_date nationality  \
2379  gpMOzKV7Qz  Kekuta Manneh  1994-12-30      Gambia

     primary_broad_position primary_general_position secondary_broad_position  \
2379                     MF                        W                      NaN

     secondary_general_position  \
2379                        NaN

                                           season_name  height_ft  height_in  \
2379  [2013, 2014, 2015, 2016, 2017, 2019, 2020, 2021]        5.0        9.0

      weight_lb competition
2379      146.0         mls
       player_id        player_name  birth_date nationality  \
2736  KXMekOprq6  Sebastián Driussi  1996-02-09   Argentina

     primary_broad_position primary_general_position secondary_broad_position  \
2736                     MF                       AM                      NaN

     secondary_general_position               season_name  height_ft  \
2736                        NaN  [2021, 2022, 2023, 2024]        5.0

      height_in  weight_lb competition
2736       10.0      176.0         mls
       player_id      player_name  birth_date nationality  \
2746  KXMeOaaPq6  Emiliano Rigoni  1993-02-04   Argentina

     primary_broad_position primary_general_position secondary_broad_position  \
2746                     MF                        W                      NaN

     secondary_general_position         season_name  height_ft  height_in  \
2746                        NaN  [2022, 2023, 2024]        5.0       11.0

      weight_lb competition
2746      154.0         mls
       player_id   player_name  birth_date nationality primary_broad_position  \
2763  ljqE2ekNQx  Zan Kolmanic  2000-03-03    Slovenia                     DF

     primary_general_position secondary_broad_position  \
2763                       FB                      NaN

     secondary_general_position               season_name  height_ft  \
2763                        NaN  [2021, 2022, 2023, 2024]        NaN

      height_in  weight_lb competition
2763        NaN        NaN         mls
       player_id     player_name  birth_date nationality  \
2770  ljqE2PwVQx  Memo Rodríguez  1995-12-27         USA
5960  ljqE2PwVQx  Memo Rodríguez  1995-12-27         USA

     primary_broad_position primary_general_position secondary_broad_position  \
2770                     MF                        W                      NaN
5960                     MF                        W                      NaN

     secondary_general_position  \
2770                         CM
5960                        NaN

                                           season_name  height_ft  height_in  \
2770  [2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]        5.0        8.0
5960                                [2017, 2018, 2019]        5.0        8.0

      weight_lb competition
2770      146.0         mls
5960      146.0        uslc
       player_id     player_name  birth_date nationality  \
2787  ljqEjLaEQx  Diego Fagundez  1995-02-14     Uruguay

     primary_broad_position primary_general_position secondary_broad_position  \
2787                     MF                        W                      NaN

     secondary_general_position  \
2787                        NaN

                                            season_name  height_ft  height_in  \
2787  [2013, 2014, 2015, 2016, 2017, 2018, 2019, 202...        5.0        8.0

      weight_lb competition
2787      141.0         mls
       player_id      player_name  birth_date nationality  \