In [2]:
import pandas as pd
from statsbombpy import sb
from mplsoccer import Pitch

In [3]:
sb.competitions()
allcomps = pd.DataFrame(sb.competitions())
for index, row in allcomps.iterrows():
    print(f"Competition Name: {row['competition_name']}, Competition ID: {row['competition_id']}, Season ID: {row['season_id']}")

Competition Name: 1. Bundesliga, Competition ID: 9, Season ID: 281
Competition Name: 1. Bundesliga, Competition ID: 9, Season ID: 27
Competition Name: African Cup of Nations, Competition ID: 1267, Season ID: 107
Competition Name: Champions League, Competition ID: 16, Season ID: 4
Competition Name: Champions League, Competition ID: 16, Season ID: 1
Competition Name: Champions League, Competition ID: 16, Season ID: 2
Competition Name: Champions League, Competition ID: 16, Season ID: 27
Competition Name: Champions League, Competition ID: 16, Season ID: 26
Competition Name: Champions League, Competition ID: 16, Season ID: 25
Competition Name: Champions League, Competition ID: 16, Season ID: 24
Competition Name: Champions League, Competition ID: 16, Season ID: 23
Competition Name: Champions League, Competition ID: 16, Season ID: 22
Competition Name: Champions League, Competition ID: 16, Season ID: 21
Competition Name: Champions League, Competition ID: 16, Season ID: 41
Competition Name: Champions League, Competition ID: 16, Season ID: 39
Competition Name: Champions League, Competition ID: 16, Season ID: 37
Competition Name: Champions League, Competition ID: 16, Season ID: 44
Competition Name: Champions League, Competition ID: 16, Season ID: 76
Competition Name: Champions League, Competition ID: 16, Season ID: 277
Competition Name: Champions League, Competition ID: 16, Season ID: 71
Competition Name: Champions League, Competition ID: 16, Season ID: 276
Competition Name: Copa America, Competition ID: 223, Season ID: 282
Competition Name: Copa del Rey, Competition ID: 87, Season ID: 84
Competition Name: Copa del Rey, Competition ID: 87, Season ID: 268
Competition Name: Copa del Rey, Competition ID: 87, Season ID: 279
Competition Name: FA Women's Super League, Competition ID: 37, Season ID: 90
Competition Name: FA Women's Super League, Competition ID: 37, Season ID: 42
Competition Name: FA Women's Super League, Competition ID: 37, Season ID: 4
Competition Name: FIFA U20 World Cup, Competition ID: 1470, Season ID: 274
Competition Name: FIFA World Cup, Competition ID: 43, Season ID: 106
Competition Name: FIFA World Cup, Competition ID: 43, Season ID: 3
Competition Name: FIFA World Cup, Competition ID: 43, Season ID: 55
Competition Name: FIFA World Cup, Competition ID: 43, Season ID: 54
Competition Name: FIFA World Cup, Competition ID: 43, Season ID: 51
Competition Name: FIFA World Cup, Competition ID: 43, Season ID: 272
Competition Name: FIFA World Cup, Competition ID: 43, Season ID: 270
Competition Name: FIFA World Cup, Competition ID: 43, Season ID: 269
Competition Name: Indian Super league, Competition ID: 1238, Season ID: 108
Competition Name: La Liga, Competition ID: 11, Season ID: 90
Competition Name: La Liga, Competition ID: 11, Season ID: 42
Competition Name: La Liga, Competition ID: 11, Season ID: 4
Competition Name: La Liga, Competition ID: 11, Season ID: 1
Competition Name: La Liga, Competition ID: 11, Season ID: 2
Competition Name: La Liga, Competition ID: 11, Season ID: 27
Competition Name: La Liga, Competition ID: 11, Season ID: 26
Competition Name: La Liga, Competition ID: 11, Season ID: 25
Competition Name: La Liga, Competition ID: 11, Season ID: 24
Competition Name: La Liga, Competition ID: 11, Season ID: 23
Competition Name: La Liga, Competition ID: 11, Season ID: 22
Competition Name: La Liga, Competition ID: 11, Season ID: 21
Competition Name: La Liga, Competition ID: 11, Season ID: 41
Competition Name: La Liga, Competition ID: 11, Season ID: 40
Competition Name: La Liga, Competition ID: 11, Season ID: 39
Competition Name: La Liga, Competition ID: 11, Season ID: 38
Competition Name: La Liga, Competition ID: 11, Season ID: 37
Competition Name: La Liga, Competition ID: 11, Season ID: 278
Competition Name: Liga Profesional, Competition ID: 81, Season ID: 48
Competition Name: Liga Profesional, Competition ID: 81, Season ID: 275
Competition Name: Ligue 1, Competition ID: 7, Season ID: 235
Competition Name: Ligue 1, Competition ID: 7, Season ID: 108
Competition Name: Ligue 1, Competition ID: 7, Season ID: 27
Competition Name: Major League Soccer, Competition ID: 44, Season ID: 107
Competition Name: North American League, Competition ID: 116, Season ID: 68
Competition Name: NWSL, Competition ID: 49, Season ID: 3
Competition Name: Premier League, Competition ID: 2, Season ID: 27
Competition Name: Premier League, Competition ID: 2, Season ID: 44
Competition Name: Serie A, Competition ID: 12, Season ID: 27
Competition Name: Serie A, Competition ID: 12, Season ID: 86
Competition Name: UEFA Euro, Competition ID: 55, Season ID: 282
Competition Name: UEFA Euro, Competition ID: 55, Season ID: 43
Competition Name: UEFA Europa League, Competition ID: 35, Season ID: 75
Competition Name: UEFA Women's Euro, Competition ID: 53, Season ID: 106
Competition Name: Women's World Cup, Competition ID: 72, Season ID: 107
Competition Name: Women's World Cup, Competition ID: 72, Season ID: 30

MLS ID = 44 on sb

In [4]:
sb.matches(competition_id=2, season_id=44) ## Invincibles

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3749052,2004-02-07,16:00:00.000,England - Premier League,2003/2004,Wolverhampton Wanderers,Arsenal,1,3,available,...,2021-06-13T16:17:31.694,2,Regular Season,Molineux Stadium,NaN,Dave Jones,Arsène Wenger,1.1.0,2,2
1,3749522,2003-12-26,13:00:00.000,England - Premier League,2003/2004,Arsenal,Wolverhampton Wanderers,3,0,available,...,2021-06-13T16:17:31.694,18,Regular Season,Highbury Stadium,NaN,Arsène Wenger,Dave Jones,1.1.0,2,2
2,3749246,2004-03-28,17:05:00.000,England - Premier League,2003/2004,Arsenal,Manchester United,1,1,available,...,2021-06-13T16:17:31.694,30,Regular Season,Highbury Stadium,NaN,Arsène Wenger,Alex Ferguson,1.1.0,2,2
3,3749257,2004-05-15,16:00:00.000,England - Premier League,2003/2004,Arsenal,Leicester City,2,1,available,...,2021-06-13T16:17:31.694,38,Regular Season,Highbury Stadium,NaN,Arsène Wenger,Micky Adams,1.1.0,2,2
4,3749642,2004-02-28,16:00:00.000,England - Premier League,2003/2004,Arsenal,Charlton Athletic,2,1,available,...,2021-06-13T16:17:31.694,27,Regular Season,Highbury Stadium,NaN,Arsène Wenger,Alan Curbishley,1.1.0,2,2
5,3749358,2003-08-24,17:05:00.000,England - Premier League,2003/2004,Middlesbrough,Arsenal,0,4,available,...,2021-06-13T16:17:31.694,1,Regular Season,Riverside Stadium,NaN,Steve McClaren,Arsène Wenger,1.1.0,2,2
6,3749346,2003-11-01,16:00:00.000,England - Premier League,2003/2004,Leeds United,Arsenal,1,4,available,...,2021-06-13T16:17:31.694,1,Regular Season,Elland Road,NaN,Peter Reid,Arsène Wenger,1.1.0,2,2
7,3749253,2003-10-04,13:30:00.000,England - Premier League,2003/2004,Liverpool,Arsenal,1,2,available,...,2021-06-13T16:17:31.694,1,Regular Season,Anfield,NaN,,,1.1.0,2,2
8,3749079,2003-10-18,16:00:00.000,England - Premier League,2003/2004,Arsenal,Chelsea,2,1,available,...,2021-06-13T16:17:31.694,9,Regular Season,Highbury Stadium,NaN,Arsène Wenger,Claudio Ranieri,1.1.0,2,2
9,3749465,2004-03-13,16:00:00.000,England - Premier League,2003/2004,Blackburn Rovers,Arsenal,0,2,available,...,2021-06-13T16:17:31.694,2,Regular Season,Ewood Park,NaN,Graeme Souness,Arsène Wenger,1.1.0,2,2
10,3749133,2004-01-18,15:00:00.000,England - Premier League,2003/2004,Aston Villa,Arsenal,0,2,available,...,2021-06-13T16:17:31.694,2,Regular Season,Villa Park,NaN,David O''Leary,Arsène Wenger,1.1.0,2,2
11,3749528,2003-09-26,21:00:00.000,England - Premier League,2003/2004,Arsenal,Newcastle United,3,2,available,...,2021-06-13T16:17:31.694,7,Regular Season,Highbury Stadium,NaN,Arsène Wenger,Bobby Robson,1.1.0,2,2
12,3749233,2004-02-01,17:05:00.000,England - Premier League,2003/2004,Arsenal,Manchester City,2,1,available,...,2021-06-13T16:17:31.694,23,Regular Season,Highbury Stadium,NaN,Arsène Wenger,Kevin Joseph Keegan,1.1.0,2,2
13,3749462,2004-05-01,13:30:00.000,England - Premier League,2003/2004,Arsenal,Birmingham City,0,0,available,...,2021-06-13T16:17:31.694,35,Regular Season,Highbury Stadium,NaN,Arsène Wenger,Steve Bruce,1.1.0,2,2
14,3749552,2003-09-21,17:05:00.000,England - Premier League,2003/2004,Manchester United,Arsenal,0,0,available,...,2021-06-13T16:17:31.694,1,Regular Season,Old Trafford,NaN,Alex Ferguson,Arsène Wenger,1.1.0,2,2
15,3749296,2003-09-13,16:00:00.000,England - Premier League,2003/2004,Arsenal,Portsmouth,1,1,available,...,2021-06-13T16:17:31.694,5,Regular Season,Highbury Stadium,NaN,Arsène Wenger,Harry Redknapp,1.1.0,2,2
16,3749454,2003-08-31,17:05:00.000,England - Premier League,2003/2004,Manchester City,Arsenal,1,2,available,...,2021-06-13T16:17:31.694,1,Regular Season,Etihad Stadium,NaN,Kevin Joseph Keegan,Arsène Wenger,1.1.0,2,2
17,3749276,2004-02-21,13:30:00.000,England - Premier League,2003/2004,Chelsea,Arsenal,1,2,available,...,2021-06-13T16:17:31.694,2,Regular Season,Stamford Bridge,NaN,Claudio Ranieri,Arsène Wenger,1.1.0,2,2
18,3749068,2004-04-25,17:05:00.000,England - Premier League,2003/2004,Tottenham Hotspur,Arsenal,2,2,available,...,2021-06-13T16:17:31.694,2,Regular Season,White Hart Lane,NaN,David Pleat,Arsène Wenger,1.1.0,2,2
19,3749310,2003-12-29,21:00:00.000,England - Premier League,2003/2004,Southampton,Arsenal,0,1,available,...,2021-06-13T16:17:31.694,1,Regular Season,St. Mary''s Stadium,NaN,Gordon Strachan,Arsène Wenger,1.1.0,2,2
20,3749493,2003-08-16,16:00:00.000,England - Premier League,2003/2004,Arsenal,Everton,2,1,available,...,2021-06-13T16:17:31.694,1,Regular Season,Highbury Stadium,NaN,Arsène Wenger,David Moyes,1.1.0,2,2
21,3749434,2003-11-22,16:00:00.000,England - Premier League,2003/2004,Birmingham City,Arsenal,0,3,available,...,2021-06-13T16:17:31.694,1,Regular Season,St. Andrews Stadium,NaN,Steve Bruce,Arsène Wenger,1.1.0,2,2
22,3749192,2003-11-30,15:00:00.000,England - Premier League,2003/2004,Arsenal,Fulham,0,0,available,...,2021-06-13T16:17:31.694,14,Regular Season,Highbury Stadium,NaN,Arsène Wenger,Chris Coleman,1.1.0,2,2
23,3749196,2003-11-08,16:00:00.000,England - Premier League,2003/2004,Arsenal,Tottenham Hotspur,2,1,available,...,2021-06-13T16:17:31.694,12,Regular Season,Highbury Stadium,NaN,Arsène Wenger,David Pleat,1.1.0,2,2
24,3749448,2004-04-09,13:30:00.000,England - Premier League,2003/2004,Arsenal,Liverpool,4,2,available,...,2021-06-13T16:17:31.694,31,Regular Season,Highbury Stadium,NaN,,,1.1.0,2,2
25,3749360,2003-12-14,15:00:00.000,England - Premier League,2003/2004,Arsenal,Blackburn Rovers,1,0,available,...,2021-06-13T16:17:31.694,16,Regular Season,Highbury Stadium,NaN,Arsène Wenger,Graeme Souness,1.1.0,2,2
26,3749453,2004-04-16,21:00:00.000,England - Premier League,2003/2004,Arsenal,Leeds United,5,0,available,...,2021-06-13T16:17:31.694,33,Regular Season,Highbury Stadium,NaN,Arsène Wenger,Eddie Gray,1.1.0,2,2
27,3749278,2003-12-20,16:00:00.000,England - Premier League,2003/2004,Bolton Wanderers,Arsenal,1,1,available,...,2021-06-13T16:17:31.694,1,Regular Season,University of Bolton Stadium,NaN,Sam Allardyce,Arsène Wenger,1.1.0,2,2
28,3749603,2004-05-09,17:05:00.000,England - Premier League,2003/2004,Fulham,Arsenal,0,1,available,...,2021-06-13T16:17:31.694,2,Regular Season,Loftus Road,NaN,Chris Coleman,Arsène Wenger,1.1.0,2,2
29,3749274,2004-05-04,21:00:00.000,England - Premier League,2003/2004,Portsmouth,Arsenal,1,1,available,...,2021-06-12T16:17:31.694,2,Regular Season,NaN,Michael Riley,Harry Redknapp,Arsène Wenger,1.1.0,2,2
30,3749590,2003-12-06,16:00:00.000,England - Premier League,2003/2004,Leicester City,Arsenal,1,1,available,...,2021-06-12T16:17:31.694,1,Regular Season,NaN,Robert Styles,Micky Adams,Arsène Wenger,1.1.0,2,2
31,3749631,2004-02-10,20:45:00.000,England - Premier League,2003/2004,Arsenal,Southampton,2,0,available,...,2021-06-12T16:17:31.694,25,Regular Season,NaN,Neale Barry,Arsène Wenger,Gordon Strachan,1.1.0,2,2
32,3749117,2004-01-07,21:00:00.000,England - Premier League,2003/2004,Everton,Arsenal,1,1,available,...,2021-06-12T16:17:31.694,2,Regular Season,NaN,Alan Wiley,David Moyes,Arsène Wenger,1.1.0,2,2
33,3749108,2003-08-27,20:45:00.000,England - Premier League,2003/2004,Arsenal,Aston Villa,2,0,available,...,2021-06-12T16:17:31.694,3,Regular Season,NaN,NaN,Arsène Wenger,David O''Leary,1.1.0,2,2
34,3749153,2004-01-10,16:00:00.000,England - Premier League,2003/2004,Arsenal,Middlesbrough,4,1,available,...,2021-06-13T16:17:31.694,21,Regular Season,Highbury Stadium,NaN,Arsène Wenger,Steve McClaren,1.1.0,2,2
35,3749403,2004-03-20,16:00:00.000,England - Premier League,2003/2004,Arsenal,Bolton Wanderers,2,1,available,...,2021-06-13T16:17:31.694,29,Regular Season,Highbury Stadium,NaN,Arsène Wenger,Sam Allardyce,1.1.0,2,2
36,3749526,2003-10-26,15:00:00.000,England - Premier League,2003/2004,Charlton Athletic,Arsenal,1,1,available,...,2021-06-13T16:17:31.694,1,Regular Season,The Valley,NaN,Alan Curbishley,Arsène Wenger,1.1.0,2,2
37,3749431,2004-04-11,17:05:00.000,England - Premier League,2003/2004,Newcastle United,Arsenal,0,0,available,...,2021-06-13T16:17:31.694,2,Regular Season,St. James'' Park,NaN,Bobby Robson,Arsène Wenger,1.1.0,2,2

In [5]:
sb.matches(competition_id=55, season_id=282) ## Last EURO

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3942819,2024-07-10,22:00:00.000,Europe - UEFA Euro,2024,Netherlands,England,1,2,available,...,2024-07-15T07:57:36.684453,6,Semi-finals,Signal-Iduna-Park,Felix Zwayer,Ronald Koeman,Gareth Southgate,1.1.0,2,2
1,3943043,2024-07-14,22:00:00.000,Europe - UEFA Euro,2024,Spain,England,2,1,available,...,2024-07-15T15:52:24.778809,7,Final,Olympiastadion Berlin,François Letexier,Luis de la Fuente Castillo,Gareth Southgate,1.1.0,2,2
2,3942752,2024-07-09,22:00:00.000,Europe - UEFA Euro,2024,Spain,France,2,1,available,...,2024-07-10T13:01:26.597509,6,Semi-finals,Allianz Arena,Slavko Vinčić,Luis de la Fuente Castillo,Didier Deschamps,1.1.0,2,2
3,3942382,2024-07-06,22:00:00.000,Europe - UEFA Euro,2024,Netherlands,Turkey,2,1,available,...,2024-07-10T06:56:35.146850,5,Quarter-finals,Olympiastadion Berlin,Clément Turpin,Ronald Koeman,Vincenzo Montella,1.1.0,2,2
4,3942349,2024-07-05,22:00:00.000,Europe - UEFA Euro,2024,Portugal,France,0,0,available,...,2024-07-12T02:00:16.871522,5,Quarter-finals,Volksparkstadion,Michael Oliver,Roberto Martínez Montoliú,Didier Deschamps,1.1.0,2,2
5,3930180,2024-06-25,19:00:00.000,Europe - UEFA Euro,2024,Netherlands,Austria,2,3,available,...,2024-07-11T13:25:37.289456,3,Group Stage,Olympiastadion Berlin,Ivan Kružliak,Ronald Koeman,Ralf Rangnick,1.1.0,2,2
6,3930171,2024-06-20,19:00:00.000,Europe - UEFA Euro,2024,Denmark,England,1,1,available,...,2024-07-12T05:19:44.572914,2,Group Stage,Deutsche Bank Park,Artur Manuel Ribeiro Soares Dias,Kasper Hjulmand,Gareth Southgate,1.1.0,2,2
7,3942227,2024-07-06,19:00:00.000,Europe - UEFA Euro,2024,England,Switzerland,1,1,available,...,2024-07-14T15:57:51.414762,5,Quarter-finals,Merkur Spiel-Arena,Daniele Orsato,Gareth Southgate,Murat Yakin,1.1.0,2,2
8,3942226,2024-07-05,19:00:00.000,Europe - UEFA Euro,2024,Spain,Germany,2,1,available,...,2024-07-13T03:52:43.383929,5,Quarter-finals,MHPArena,Anthony Taylor,Luis de la Fuente Castillo,Julian Nagelsmann,1.1.0,2,2
9,3938645,2024-06-26,19:00:00.000,Europe - UEFA Euro,2024,Ukraine,Belgium,0,0,available,...,2024-07-11T16:17:18.090189,3,Group Stage,MHPArena,Anthony Taylor,Sergiy Rebrov,Domenico Tedesco,1.1.0,2,2
10,3930184,2024-06-26,22:00:00.000,Europe - UEFA Euro,2024,Czech Republic,Turkey,1,2,available,...,2024-07-10T11:03:55.105146,3,Group Stage,Volksparkstadion,István Kovács,Ivan Hašek,Vincenzo Montella,1.1.0,2,2
11,3941022,2024-07-02,22:00:00.000,Europe - UEFA Euro,2024,Austria,Turkey,1,2,available,...,2024-07-10T11:31:13.553408,4,Round of 16,Red Bull Arena,Artur Manuel Ribeiro Soares Dias,Ralf Rangnick,Vincenzo Montella,1.1.0,2,2
12,3941021,2024-07-02,19:00:00.000,Europe - UEFA Euro,2024,Romania,Netherlands,0,3,available,...,2024-07-12T23:28:27.122555,4,Round of 16,Allianz Arena,Felix Zwayer,Edward Iordănescu,Ronald Koeman,1.1.0,2,2
13,3941020,2024-07-01,22:00:00.000,Europe - UEFA Euro,2024,Portugal,Slovenia,0,0,available,...,2024-07-13T19:48:57.256302,4,Round of 16,Deutsche Bank Park,Daniele Orsato,Roberto Martínez Montoliú,Matjaž Kek,1.1.0,2,2
14,3941019,2024-07-01,19:00:00.000,Europe - UEFA Euro,2024,France,Belgium,1,0,available,...,2024-07-10T11:04:16.590488,4,Round of 16,Merkur Spiel-Arena,Glenn Nyberg,Didier Deschamps,Domenico Tedesco,1.1.0,2,2
15,3941018,2024-06-30,22:00:00.000,Europe - UEFA Euro,2024,Spain,Georgia,4,1,available,...,2024-07-12T06:08:12.572176,4,Round of 16,RheinEnergieStadion,François Letexier,Luis de la Fuente Castillo,Willy Sagnol,1.1.0,2,2
16,3941017,2024-06-30,19:00:00.000,Europe - UEFA Euro,2024,England,Slovakia,2,1,available,...,2024-07-10T11:31:44.852038,4,Round of 16,VELTINS-Arena,Halil Umut Meler,Gareth Southgate,Francesco Calzona,1.1.0,2,2
17,3930182,2024-06-25,22:00:00.000,Europe - UEFA Euro,2024,Denmark,Serbia,0,0,available,...,2024-07-10T09:19:06.030329,3,Group Stage,Allianz Arena,François Letexier,Kasper Hjulmand,Dragan Stojković,1.1.0,2,2
18,3930179,2024-06-24,22:00:00.000,Europe - UEFA Euro,2024,Albania,Spain,0,1,available,...,2024-07-01T06:07:22.418137,3,Group Stage,Merkur Spiel-Arena,Glenn Nyberg,Sylvio Mendes Campos Junior,Luis de la Fuente Castillo,1.1.0,2,2
19,3940983,2024-06-29,22:00:00.000,Europe - UEFA Euro,2024,Germany,Denmark,2,0,available,...,2024-07-07T11:16:18.087539,4,Round of 16,Signal-Iduna-Park,Michael Oliver,Julian Nagelsmann,Kasper Hjulmand,1.1.0,2,2
20,3940878,2024-06-29,19:00:00.000,Europe - UEFA Euro,2024,Switzerland,Italy,2,0,available,...,2024-07-12T01:32:19.577126,4,Round of 16,Olympiastadion Berlin,Szymon Marciniak,Murat Yakin,Luciano Spalletti,1.1.0,2,2
21,3930177,2024-06-23,22:00:00.000,Europe - UEFA Euro,2024,Scotland,Hungary,0,1,available,...,2024-07-10T14:56:29.359087,3,Group Stage,MHPArena,Facundo Tello Figueroa,Steve Clarke,Marco Rossi,1.1.0,2,2
22,3930173,2024-06-21,22:00:00.000,Europe - UEFA Euro,2024,Netherlands,France,0,0,available,...,2024-07-12T19:39:43.381031,2,Group Stage,Trainingszentrum RB Leipzig Platz 1,Anthony Taylor,Ronald Koeman,Didier Deschamps,1.1.0,2,2
23,3930172,2024-06-20,22:00:00.000,Europe - UEFA Euro,2024,Spain,Italy,1,0,available,...,2024-07-12T00:16:51.275112,2,Group Stage,VELTINS-Arena,Slavko Vinčić,Luis de la Fuente Castillo,Luciano Spalletti,1.1.0,2,2
24,3930167,2024-06-19,16:00:00.000,Europe - UEFA Euro,2024,Croatia,Albania,2,2,available,...,2024-07-11T08:18:46.582123,2,Group Stage,Volksparkstadion,François Letexier,Zlatko Dalić,Sylvio Mendes Campos Junior,1.1.0,2,2
25,3930168,2024-06-19,19:00:00.000,Europe - UEFA Euro,2024,Germany,Hungary,2,0,available,...,2024-07-11T14:24:30.771631,2,Group Stage,MHPArena,Danny Desmond Makkelie,Julian Nagelsmann,Marco Rossi,1.1.0,2,2
26,3930165,2024-06-17,22:00:00.000,Europe - UEFA Euro,2024,Austria,France,0,1,available,...,2024-07-13T18:19:14.500227,1,Group Stage,Merkur Spiel-Arena,Jesús Gil Manzano,Ralf Rangnick,Didier Deschamps,1.1.0,2,2
27,3930164,2024-06-17,19:00:00.000,Europe - UEFA Euro,2024,Belgium,Slovakia,0,1,available,...,2024-07-14T00:00:18.546176,1,Group Stage,Deutsche Bank Park,Halil Umut Meler,Domenico Tedesco,Francesco Calzona,1.1.0,2,2
28,3930161,2024-06-15,22:00:00.000,Europe - UEFA Euro,2024,Italy,Albania,2,1,available,...,2024-07-12T05:16:16.043874,1,Group Stage,Signal-Iduna-Park,Felix Zwayer,Luciano Spalletti,Sylvio Mendes Campos Junior,1.1.0,2,2
29,3938637,2024-06-16,16:00:00.000,Europe - UEFA Euro,2024,Poland,Netherlands,1,2,available,...,2024-07-12T03:39:53.010211,1,Group Stage,Volksparkstadion,Artur Manuel Ribeiro Soares Dias,Michał Probierz,Ronald Koeman,1.1.0,2,2
30,3938640,2024-06-21,16:00:00.000,Europe - UEFA Euro,2024,Slovakia,Ukraine,1,2,available,...,2024-07-12T18:56:00.519961,2,Group Stage,Merkur Spiel-Arena,Michael Oliver,Francesco Calzona,Sergiy Rebrov,1.1.0,2,2
31,3938642,2024-06-22,16:00:00.000,Europe - UEFA Euro,2024,Georgia,Czech Republic,1,1,available,...,2024-07-09T12:53:31.025418,2,Group Stage,Volksparkstadion,Daniel Siebert,Willy Sagnol,Ivan Hašek,1.1.0,2,2
32,3938639,2024-06-18,19:00:00.000,Europe - UEFA Euro,2024,Turkey,Georgia,3,1,available,...,2024-07-12T06:05:10.871017,1,Group Stage,Signal-Iduna-Park,Facundo Tello Figueroa,Vincenzo Montella,Willy Sagnol,1.1.0,2,2
33,3938641,2024-06-21,19:00:00.000,Europe - UEFA Euro,2024,Poland,Austria,1,3,available,...,2024-07-12T21:10:46.438024,2,Group Stage,Olympiastadion Berlin,Halil Umut Meler,Michał Probierz,Ralf Rangnick,1.1.0,2,2
34,3938644,2024-06-26,22:00:00.000,Europe - UEFA Euro,2024,Georgia,Portugal,2,0,available,...,2024-07-12T05:42:21.069872,3,Group Stage,VELTINS-Arena,Sandro Schärer,Willy Sagnol,Roberto Martínez Montoliú,1.1.0,2,2
35,3938643,2024-06-25,19:00:00.000,Europe - UEFA Euro,2024,France,Poland,1,1,available,...,2024-07-12T06:08:47.869486,3,Group Stage,Signal-Iduna-Park,Marco Guida,Didier Deschamps,Michał Probierz,1.1.0,2,2
36,3938638,2024-06-17,16:00:00.000,Europe - UEFA Euro,2024,Romania,Ukraine,3,0,available,...,2024-07-12T03:39:18.794242,1,Group Stage,Allianz Arena,Glenn Nyberg,Edward Iordănescu,Sergiy Rebrov,1.1.0,2,2
37,3930183,2024-06-26,19:00:00.000,Europe - UEFA Euro,2024,Slovakia,Romania,1,1,available,...,2024-07-09T16:16:22.181617,3,Group Stage,Deutsche Bank Park,Daniel Siebert,Francesco Calzona,Edward Iordănescu,1.1.0,2,2
38,3930181,2024-06-25,22:00:00.000,Europe - UEFA Euro,2024,England,Slovenia,0,0,available,...,2024-07-10T14:27:59.561474,3,Group Stage,RheinEnergieStadion,Clément Turpin,Gareth Southgate,Matjaž Kek,1.1.0,2,2
39,3930178,2024-06-24,22:00:00.000,Europe - UEFA Euro,2024,Croatia,Italy,1,1,available,...,2024-07-10T12:23:12.394850,3,Group Stage,Red Bull Arena,Danny Desmond Makkelie,Zlatko Dalić,Luciano Spalletti,1.1.0,2,2
40,3930176,2024-06-23,22:00:00.000,Europe - UEFA Euro,2024,Switzerland,Germany,1,1,available,...,2024-07-13T21:41:29.142800,3,Group Stage,Deutsche Bank Park,Daniele Orsato,Murat Yakin,Julian Nagelsmann,1.1.0,2,2
41,3930175,2024-06-22,22:00:00.000,Europe - UEFA Euro,2024,Belgium,Romania,2,0,available,...,2024-07-09T15:13:58.718506,2,Group Stage,RheinEnergieStadion,Szymon Marciniak,Domenico Tedesco,Edward Iordănescu,1.1.0,2,2
42,3930174,2024-06-22,19:00:00.000,Europe - UEFA Euro,2024,Turkey,Portugal,0,3,available,...,2024-07-11T16:43:45.852125,2,Group Stage,Signal-Iduna-Park,Felix Zwayer,Vincenzo Montella,Roberto Martínez Montoliú,1.1.0,2,2
43,3930170,2024-06-20,16:00:00.000,Europe - UEFA Euro,2024,Slovenia,Serbia,1,1,available,...,2024-07-12T18:53:31.866826,2,Group Stage,Allianz Arena,István Kovács,Matjaž Kek,Dragan Stojković,1.1.0,2,2
44,3930169,2024-06-19,22:00:00.000,Europe - UEFA Euro,2024,Scotland,Switzerland,1,1,available,...,2024-07-14T00:02:35.662811,2,Group Stage,RheinEnergieStadion,Ivan Kružliak,Steve Clarke,Murat Yakin,1.1.0,2,2
45,3930166,2024-06-18,22:00:00.000,Europe - UEFA Euro,2024,Portugal,Czech Republic,2,1,available,...,2024-07-10T14:54:55.319751,1,Group Stage,Red Bull Arena,Marco Guida,Roberto Martínez Montoliú,Ivan Hašek,1.1.0,2,2
46,3930163,2024-06-16,22:00:00.000,Europe - UEFA Euro,2024,Serbia,England,0,1,available,...,2024-07-14T07:10:41.937955,1,Group Stage,VELTINS-Arena,Daniele Orsato,Dragan Stojković,Gareth Southgate,1.1.0,2,2
47,3930162,2024-06-16,19:00:00.000,Europe - UEFA Euro,2024,Slovenia,Denmark,1,1,available,...,2024-07-10T16:09:27.468163,1,Group Stage,MHPArena,Sandro Schärer,Matjaž Kek,Kasper Hjulmand,1.1.0,2,2
48,3930160,2024-06-15,19:00:00.000,Europe - UEFA Euro,2024,Spain,Croatia,3,0,available,...,2024-07-12T03:40:20.513429,1,Group Stage,Olympiastadion Berlin,Michael Oliver,Luis de la Fuente Castillo,Zlatko Dalić,1.1.0,2,2
49,3930159,2024-06-15,16:00:00.000,Europe - UEFA Euro,2024,Hungary,Switzerland,1,3,available,...,2024-07-10T13:35:35.263551,1,Group Stage,RheinEnergieStadion,Slavko Vinčić,Marco Rossi,Murat Yakin,1.1.0,2,2
50,3930158,2024-06-14,22:00:00.000,Europe - UEFA Euro,2024,Germany,Scotland,5,1,available,...,2024-07-04T08:13:19.028344,1,Group Stage,Allianz Arena,Clément Turpin,Julian Nagelsmann,Steve Clarke,1.1.0,2,2

In [6]:
sb.matches(competition_id=223, season_id=282) # Last Copa

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3943077,2024-07-15,04:15:00.000,South America - Copa America,2024,Argentina,Colombia,1,0,available,...,None,6,Final,Hard Rock Stadium,Raphael Claus,Lionel Sebastián Scaloni,Néstor Gabriel Lorenzo,1.1.0,2,2
1,3943076,2024-07-14,03:00:00.000,South America - Copa America,2024,Canada,Uruguay,2,2,available,...,None,6,3rd Place Final,Bank of America Stadium,Alexis Herrera,Jesse Marsch,Marcelo Alberto Bielsa Caldera,1.1.0,2,2
2,3942852,2024-07-11,03:00:00.000,South America - Copa America,2024,Uruguay,Colombia,0,1,available,...,None,5,Semi-finals,Bank of America Stadium,César Arturo Ramos Palazuelos,Marcelo Alberto Bielsa Caldera,Néstor Gabriel Lorenzo,1.1.0,2,2
3,3942785,2024-07-10,03:00:00.000,South America - Copa America,2024,Argentina,Canada,2,0,available,...,None,5,Semi-finals,MetLife Stadium,Piero Maza Gomez,Lionel Sebastián Scaloni,Jesse Marsch,1.1.0,2,2
4,3942416,2024-07-07,01:00:00.000,South America - Copa America,2024,Colombia,Panama,5,0,available,...,None,4,Quarter-finals,State Farm Stadium,Maurizio Mariani,Néstor Gabriel Lorenzo,Thomas Christiansen Tarín,1.1.0,2,2
5,3942415,2024-07-07,04:00:00.000,South America - Copa America,2024,Uruguay,Brazil,0,0,available,...,None,4,Quarter-finals,Allegiant Stadium,Darío Herrera,Marcelo Alberto Bielsa Caldera,Dorival Silvestre Júnior,1.1.0,2,2
6,3939986,2024-06-30,03:00:00.000,South America - Copa America,2024,Argentina,Peru,2,0,available,...,None,3,Group Stage,Hard Rock Stadium,César Arturo Ramos Palazuelos,Lionel Sebastián Scaloni,Jorge Daniel Fossati Lurachi,1.1.0,2,2
7,3939973,2024-06-24,04:00:00.000,South America - Copa America,2024,Uruguay,Panama,3,1,available,...,None,1,Group Stage,Hard Rock Stadium,Piero Maza Gomez,Marcelo Alberto Bielsa Caldera,Thomas Christiansen Tarín,1.1.0,2,2
8,3942229,2024-07-06,04:00:00.000,South America - Copa America,2024,Venezuela,Canada,1,1,available,...,None,4,Quarter-finals,AT&T Stadium,Wilton Pereira Sampaio,Fernando Ariel Batista,Jesse Marsch,1.1.0,2,2
9,3942228,2024-07-05,04:00:00.000,South America - Copa America,2024,Argentina,Ecuador,1,1,available,...,None,4,Quarter-finals,NRG Stadium,Andrés Matonte,Lionel Sebastián Scaloni,Félix Sánchez Bas,1.1.0,2,2
10,3939985,2024-06-30,03:00:00.000,South America - Copa America,2024,Canada,Chile,0,0,available,...,None,3,Group Stage,Inter&Co Stadium,Wilmar Alexander Roldán Pérez,Jesse Marsch,Ricardo Alberto Gareca Nardi,1.1.0,2,2
11,3939984,2024-06-29,01:00:00.000,South America - Copa America,2024,Colombia,Costa Rica,3,0,available,...,None,2,Group Stage,State Farm Stadium,Gustavo Tejera,Néstor Gabriel Lorenzo,Gustavo Julio Alfaro,1.1.0,2,2
12,3939981,2024-06-28,01:00:00.000,South America - Copa America,2024,Panama,United States,2,1,available,...,None,2,Group Stage,Mercedes-Benz Stadium,Ivan Arcides Barton Cisneros,Thomas Christiansen Tarín,Gregg Berhalter,1.1.0,2,2
13,3939992,2024-07-03,04:00:00.000,South America - Copa America,2024,Costa Rica,Paraguay,2,1,available,...,None,3,Group Stage,Q2 Stadium,Yael Falcón Pérez,Gustavo Julio Alfaro,Daniel Oscar Garnero,1.1.0,2,2
14,3939991,2024-07-03,04:00:00.000,South America - Copa America,2024,Brazil,Colombia,1,1,available,...,None,3,Group Stage,Levi''s Stadium,Jesús Valenzuela Sáez,Dorival Silvestre Júnior,Néstor Gabriel Lorenzo,1.1.0,2,2
15,3939990,2024-07-02,04:00:00.000,South America - Copa America,2024,United States,Uruguay,0,1,available,...,None,3,Group Stage,Arrowhead Stadium,Kevin Ortega,Gregg Berhalter,Marcelo Alberto Bielsa Caldera,1.1.0,2,2
16,3939989,2024-07-02,04:00:00.000,South America - Copa America,2024,Bolivia,Panama,1,3,available,...,None,3,Group Stage,Orlando City Stadium,Edina Alves Batista,Antônio Carlos Zago,Thomas Christiansen Tarín,1.1.0,2,2
17,3939988,2024-07-01,03:00:00.000,South America - Copa America,2024,Mexico,Ecuador,0,0,available,...,None,3,Group Stage,State Farm Stadium,Mario Alberto Escobar Toca,Jaime Arturo Lozano Espín,Félix Sánchez Bas,1.1.0,2,2
18,3939987,2024-07-01,03:00:00.000,South America - Copa America,2024,Jamaica,Venezuela,0,3,available,...,None,3,Group Stage,Q2 Stadium,Maurizio Mariani,Heimir Hallgrímsson,Fernando Ariel Batista,1.1.0,2,2
19,3939983,2024-06-29,04:00:00.000,South America - Copa America,2024,Paraguay,Brazil,1,4,available,...,None,2,Group Stage,Allegiant Stadium,Piero Maza Gomez,Daniel Oscar Garnero,Dorival Silvestre Júnior,1.1.0,2,2
20,3939982,2024-06-28,04:00:00.000,South America - Copa America,2024,Uruguay,Bolivia,5,0,available,...,None,2,Group Stage,MetLife Stadium,Juan Gabriel Benítez,Marcelo Alberto Bielsa Caldera,Antônio Carlos Zago,1.1.0,2,2
21,3939980,2024-06-27,01:00:00.000,South America - Copa America,2024,Ecuador,Jamaica,3,1,available,...,None,2,Group Stage,Allegiant Stadium,Cristián Garay,Félix Sánchez Bas,Heimir Hallgrímsson,1.1.0,2,2
22,3939979,2024-06-27,04:00:00.000,South America - Copa America,2024,Venezuela,Mexico,1,0,available,...,None,2,Group Stage,SoFi Stadium,Raphael Claus,Fernando Ariel Batista,Jaime Arturo Lozano Espín,1.1.0,2,2
23,3939978,2024-06-26,01:00:00.000,South America - Copa America,2024,Peru,Canada,0,1,available,...,None,2,Group Stage,Children''s Mercy Park,Mario Alberto Escobar Toca,Jorge Daniel Fossati Lurachi,Jesse Marsch,1.1.0,2,2
24,3939977,2024-06-26,04:00:00.000,South America - Copa America,2024,Chile,Argentina,0,1,available,...,None,2,Group Stage,MetLife Stadium,Andrés Matonte,Ricardo Alberto Gareca Nardi,Lionel Sebastián Scaloni,1.1.0,2,2
25,3939976,2024-06-25,04:00:00.000,South America - Copa America,2024,Brazil,Costa Rica,0,0,available,...,None,1,Group Stage,SoFi Stadium,César Arturo Ramos Palazuelos,Dorival Silvestre Júnior,Gustavo Julio Alfaro,1.1.0,2,2
26,3939975,2024-06-25,01:00:00.000,South America - Copa America,2024,Colombia,Paraguay,2,1,available,...,None,1,Group Stage,NRG Stadium,Darío Herrera,Néstor Gabriel Lorenzo,Daniel Oscar Garnero,1.1.0,2,2
27,3939974,2024-06-24,01:00:00.000,South America - Copa America,2024,United States,Bolivia,2,0,available,...,None,1,Group Stage,AT&T Stadium,Maurizio Mariani,Gregg Berhalter,Antônio Carlos Zago,1.1.0,2,2
28,3939972,2024-06-23,01:00:00.000,South America - Copa America,2024,Ecuador,Venezuela,1,2,available,...,None,1,Group Stage,Levi''s Stadium,Wilmar Alexander Roldán Pérez,Félix Sánchez Bas,Fernando Ariel Batista,1.1.0,2,2
29,3939971,2024-06-23,04:00:00.000,South America - Copa America,2024,Mexico,Jamaica,1,0,available,...,None,1,Group Stage,NRG Stadium,Ismail Elfath,Jaime Arturo Lozano Espín,Heimir Hallgrímsson,1.1.0,2,2
30,3939970,2024-06-22,03:00:00.000,South America - Copa America,2024,Peru,Chile,0,0,available,...,None,1,Group Stage,AT&T Stadium,Wilton Pereira Sampaio,Jorge Daniel Fossati Lurachi,Ricardo Alberto Gareca Nardi,1.1.0,2,2
31,3939969,2024-06-21,03:00:00.000,South America - Copa America,2024,Argentina,Canada,2,0,available,...,None,1,Group Stage,Mercedes-Benz Stadium,Jesús Valenzuela Sáez,Lionel Sebastián Scaloni,Jesse Marsch,1.1.0,2,2

In [7]:
from itscalledsoccer.client import AmericanSoccerAnalysis

asa_client = AmericanSoccerAnalysis()

In [8]:
asa_client.get_teams(leagues="mls")

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))

,team_id,team_name,team_short_name,team_abbreviation,competition
17,0KPqjA456v,San Jose Earthquakes,San Jose,SJE,mls
18,19vQ2095K6,New England Revolution,New England,NER,mls
19,4wM42l4qjB,Chivas USA,Chivas,CHV,mls
20,9z5k7Yg5A3,Philadelphia Union,Philadelphia,PHI,mls
21,a2lqR4JMr0,Real Salt Lake,Salt Lake,RSL,mls
22,a2lqRX2Mr0,New York Red Bulls,New York,NYRB,mls
23,APk5LGOMOW,CF Montréal,Montréal,MTL,mls
24,EKXMeX3Q64,D.C. United,D.C. United,DCU,mls
25,eVq3ya6MWO,Los Angeles FC,Los Angeles FC,LAFC,mls
26,gpMOLwl5zy,Austin FC,Austin,ATX,mls
27,jYQJ19EqGR,Seattle Sounders FC,Seattle,SEA,mls
28,jYQJ8EW5GR,Orlando City SC,Orlando City,ORL,mls
29,kaDQ0wRqEv,LA Galaxy,LA Galaxy,LAG,mls
30,KAqBN0Vqbg,Atlanta United FC,Atlanta,ATL,mls
31,kRQabn8MKZ,Toronto FC,Toronto,TOR,mls
32,kRQand1MKZ,Minnesota United FC,Minnesota,MIN,mls
33,lgpMOvnQzy,Vancouver Whitecaps FC,Vancouver,VAN,mls
34,mKAqBBmqbg,FC Dallas,Dallas,FCD,mls
35,mvzqoLZQap,Columbus Crew,Columbus,CLB,mls
36,NPqxKXZ59d,Charlotte FC,Charlotte,CLT,mls
37,NWMWlBK5lz,FC Cincinnati,Cincinnati,CIN,mls
38,pzeQZ6xQKw,Colorado Rapids,Colorado,COL,mls
39,Vj58weDM8n,New York City FC,New York City,NYC,mls
40,vzqoOgNqap,Nashville SC,Nashville,NSH,mls
41,WBLMvYAQxe,Portland Timbers FC,Portland,POR,mls
42,wvq9B9wQWn,St. Louis City SC,St. Louis,STL,mls
43,X0Oq66zq6D,Chicago Fire FC,Chicago,CHI,mls
44,YgOMngl5wN,Houston Dynamo FC,Houston,HOU,mls
45,Z2vQ1xlqrA,Sporting Kansas City,Kansas City,SKC,mls
46,zeQZkL1MKw,Inter Miami CF,Miami,MIA,mls

In [9]:
df_austin_fc = asa_client.get_games(team_names="Austin FC", seasons="2024")
print(df_austin_fc)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))

       game_id            date_time_utc  home_score  away_score home_team_id  \
0   0x5gzY9PM7  2024-07-21 00:30:00 UTC           2           2   gpMOLwl5zy
1   KAqBoZ3JQb  2024-07-18 00:30:00 UTC           3           1   mKAqBBmqbg
2   xW5pJNWlQg  2024-07-14 00:30:00 UTC           0           1   gpMOLwl5zy
3   gjMNr2VvMK  2024-07-07 01:55:00 UTC           2           1   gpMOLwl5zy
4   ljqEkvWEMx  2024-06-30 00:30:00 UTC           2           0   Z2vQ1xlqrA
5   ljqEkvZzMx  2024-06-23 00:30:00 UTC           0           1   kRQand1MKZ
6   vzqozyAj5a  2024-06-20 00:30:00 UTC           1           1   gpMOLwl5zy
7   Oa5w6NpjM1  2024-06-16 01:30:00 UTC           2           0   pzeQZ6xQKw
8   XVqK7rPOq0  2024-06-02 01:30:00 UTC           5           1   a2lqR4JMr0
9   2vQ11JzKQr  2024-05-30 00:30:00 UTC           0           2   gpMOLwl5zy
10  315VzAa959  2024-05-26 02:30:00 UTC           1           1   0KPqjA456v
11  vzqozylk5a  2024-05-19 00:30:00 UTC           3           2   gpMOLwl5zy
12  9YqdzyGLMv  2024-05-16 00:30:00 UTC           1           0   gpMOLwl5zy
13  wvq9wO8wMW  2024-05-12 00:30:00 UTC           2           1   mKAqBBmqbg
14  eVq3l3DDQW  2024-05-05 02:30:00 UTC           0           0   lgpMOvnQzy
15  e7MzoN295r  2024-04-27 17:45:00 UTC           2           0   gpMOLwl5zy
16  KXMezynX56  2024-04-21 00:30:00 UTC           0           1   YgOMngl5wN
17  raMyn0xk5d  2024-04-14 20:45:00 UTC           1           0   wvq9B9wQWn
18  ljqEkvbAMx  2024-04-07 00:30:00 UTC           4           3   gpMOLwl5zy
19  KXMezybX56  2024-03-31 00:30:00 UTC           2           1   gpMOLwl5zy
20  2lqReA8A5r  2024-03-23 23:30:00 UTC           2           0   jYQJ8EW5GR
21  2lqReA825r  2024-03-17 00:30:00 UTC           2           2   gpMOLwl5zy
22  jYQJyrrWqG  2024-03-10 01:30:00 UTC           2           2   gpMOLwl5zy
23  4JMAnzz75K  2024-03-03 03:30:00 UTC           0           0   jYQJ19EqGR
24  EGMP8AArMa  2024-02-25 01:30:00 UTC           1           2   gpMOLwl5zy

   away_team_id  referee_id  stadium_id home_manager_id away_manager_id  \
0    NPqxKXZ59d  4JMAYlPMKg  jYQJZDDQGR      0Oq6mNP56D      wvq9NPNQWn
1    gpMOLwl5zy  gjMNk4v5Kp  eVq3alGMWO      zeQZyzZqKw      0Oq6mNP56D
2    jYQJ19EqGR  9z5kJ7gMA3  jYQJZDDQGR      0Oq6mNP56D      odMXxreMYL
3    Vj58weDM8n  kRQa9k8QKZ  jYQJZDDQGR      0Oq6mNP56D      gpMOPN75zy
4    gpMOLwl5zy  xW5pE3Yqg1  NPqxy6XQ9d      N6MmpyLQEG      0Oq6mNP56D
5    gpMOLwl5zy  Pk5LRpDQOW  odMXGRrQYL      KAqBEaW5bg      0Oq6mNP56D
6    eVq3ya6MWO  EGMPLlxMaY  jYQJZDDQGR      0Oq6mNP56D      NWMWxKe5lz
7    gpMOLwl5zy  ljqEymNqx0  9z5ka6gQA3      vzqo2dv5ap      0Oq6mNP56D
8    gpMOLwl5zy  e7MzjxJMr0  e7MzlRjqr0      4wM4vOAqjB      0Oq6mNP56D
9    WBLMvYAQxe  2lqRymD5r0  jYQJZDDQGR      0Oq6mNP56D      gpMOYJ7qzy
10   gpMOLwl5zy  jYQJnoVQGR  Vj58W84M8n      eV5DNVJQKn      0Oq6mNP56D
11   Z2vQ1xlqrA  Vj58OwwM8n  jYQJZDDQGR      0Oq6mNP56D      N6MmpyLQEG
12   YgOMngl5wN  e7MzPKXqr0  jYQJZDDQGR      0Oq6mNP56D      vzqoAjJMap
13   gpMOLwl5zy  9z5kJ7gMA3  eVq3alGMWO      KAqBwv7Qbg      0Oq6mNP56D
14   gpMOLwl5zy  0Oq6vG2q6D  ljqEDnO5x0      Pk5LWONMOW      0Oq6mNP56D
15   kaDQ0wRqEv  2lqRymD5r0  jYQJZDDQGR      0Oq6mNP56D      Xj5Yx60Mbd
16   gpMOLwl5zy  ljqExYw5x0  0x5g6ojM7O      vzqoAjJMap      0Oq6mNP56D
17   gpMOLwl5zy  EGMPLlxMaY  4wM4ez45jB      zeQZVw1QKw      0Oq6mNP56D
18   0KPqjA456v  2lqRG1WQr0  jYQJZDDQGR      0Oq6mNP56D      eV5DNVJQKn
19   mKAqBBmqbg  9vQ2mPaqK6  jYQJZDDQGR      0Oq6mNP56D      KAqBwv7Qbg
20   gpMOLwl5zy  EGMPEpj5aY  vzqoJrj5ap      gjMNk8v5Kp      0Oq6mNP56D
21   9z5k7Yg5A3  0x5ggRZ57O  jYQJZDDQGR      0Oq6mNP56D      0Oq6vPrq6D
22   wvq9B9wQWn  0x5gZv7M7O  jYQJZDDQGR      0Oq6mNP56D      zeQZVw1QKw
23   gpMOLwl5zy  315Vv0X59x  9Yqda07QvJ      odMXxreMYL      0Oq6mNP56D
24   kRQand1MKZ  7VqG8p3QvW  jYQJZDDQGR      0Oq6mNP56D      e7MzXrOqr0

    expanded_minutes  season_name  matchday  attendance  knockout_game  \
0                101         2024        27           0          False
1                106         2024        26           0          False
2                 98         2024        25       20738          False
3                107         2024        24       20738          False
4                 99         2024        22       18722          False
5                100         2024        21       19746          False
6                 99         2024        20       20738          False
7                 99         2024        19       17433          False
8                105         2024        17       21078          False
9                104         2024        16       20738          False
10                95         2024        15       13744          False
11               104         2024        14       20738          False
12                98         2024        13       20738          False
13               101         2024        12       19069          False
14               104         2024        11       32465          False
15                99         2024        10       20738          False
16               100         2024         9       20115          False
17               103         2024         8       22423          False
18               110         2024         7       20738          False
19               102         2024         6       20738          False
20                98         2024         5       20985          False
21               105         2024         4       20738          False
22                99         2024         3       20738          False
23               103         2024         2       30067          False
24                99         2024         1       20738          False

           last_updated_utc
0   2024-07-21 02:46:19 UTC
1   2024-07-19 12:12:20 UTC
2   2024-07-16 05:40:05 UTC
3   2024-07-10 05:14:50 UTC
4   2024-07-02 11:12:20 UTC
5   2024-06-26 08:01:34 UTC
6   2024-06-22 23:05:47 UTC
7   2024-06-18 04:49:32 UTC
8   2024-06-04 09:54:25 UTC
9   2024-06-01 10:11:26 UTC
10  2024-05-29 10:57:30 UTC
11  2024-05-21 22:43:52 UTC
12  2024-05-18 06:32:24 UTC
13  2024-05-14 06:25:20 UTC
14  2024-05-07 23:06:07 UTC
15  2024-04-30 01:45:28 UTC
16  2024-04-23 23:01:21 UTC
17  2024-04-19 13:27:51 UTC
18  2024-04-10 09:31:53 UTC
19  2024-04-03 12:03:44 UTC
20  2024-03-26 06:26:20 UTC
21  2024-03-22 11:18:56 UTC
22  2024-03-12 19:21:39 UTC
23  2024-03-05 20:11:17 UTC
24  2024-02-28 06:26:34 UTC

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))

In [10]:
asa_client.get_game_xgoals(game_id="0x5gzY9PM7")

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))

,game_id,date_time_utc,home_team_id,home_goals,home_team_xgoals,home_player_xgoals,away_team_id,away_goals,away_team_xgoals,away_player_xgoals,goal_difference,team_xgoal_difference,player_xgoal_difference,final_score_difference,home_xpoints,away_xpoints
0,0x5gzY9PM7,2024-07-21 00:30:00 UTC,gpMOLwl5zy,2,2.4055,2.4055,NPqxKXZ59d,2,2.4263,2.4263,0,-0.0208,-0.0208,0,1.442,1.322

In [11]:
players = asa_client.get_players()
print(players)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))

        player_id             player_name  birth_date nationality  \
0      0Oq6243Pq6             Lena Silano  2000-02-28         USA
1      0Oq62ob2q6            Heather Hinz         NaN         USA
2      0Oq632XPQ6         Jenna Hellstrom  1995-04-02      Canada
3      0Oq63967Q6            Julia Dorsey  2000-08-08         USA
4      0Oq63d8XQ6           Maddie Huster  1996-07-05         USA
...           ...                     ...         ...         ...
10730  zeQZXojN5K        Anthony Alaouieh  2006-07-24         USA
10731  zeQZXXm15K              Jake Davis  2002-01-03         USA
10732  zeQZXyBx5K          Maclovio Swett  2004-05-26         USA
10733  zeQZXZ9Z5K           Elijah Amadin  1999-06-16         USA
10734  zeQZXzwD5K  Sebastian Joffre Soliz  1999-08-21     Bolivia

      primary_broad_position primary_general_position  \
0                         FW                       ST
1                        NaN                      NaN
2                         DF                       FB
3                        NaN                      NaN
4                        NaN                      NaN
...                      ...                      ...
10730                     FW                        W
10731                     MF                       CM
10732                     MF                        W
10733                     DF                       FB
10734                     DF                       FB

      secondary_broad_position secondary_general_position   season_name  \
0                           MF                          W  [2023, 2024]
1                          NaN                        NaN            {}
2                          NaN                        NaN          2020
3                          NaN                        NaN            {}
4                          NaN                        NaN            {}
...                        ...                        ...           ...
10730                      NaN                        NaN  [2023, 2024]
10731                      NaN                        NaN  [2022, 2023]
10732                       FW                          W          2022
10733                      NaN                        NaN          2023
10734                       MF                          W          2024

       height_ft  height_in  weight_lb competition
0            NaN        NaN        NaN        nwsl
1            NaN        NaN        NaN        nwsl
2            5.0        6.0        NaN        nwsl
3            NaN        NaN        NaN        nwsl
4            5.0        4.0        NaN        nwsl
...          ...        ...        ...         ...
10730        NaN        NaN        NaN       mlsnp
10731        5.0       10.0      150.0       mlsnp
10732        NaN        NaN        NaN       mlsnp
10733        6.0        0.0        NaN       mlsnp
10734        5.0        8.0      150.0       mlsnp

[10735 rows x 13 columns]

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))

In [12]:
austin_players_goals_added = asa_client.get_player_goals_added(team_ids="gpMOLwl5zy")
print(austin_players_goals_added)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))

     player_id     team_id general_position  minutes_played  \
0   0Oq67EgQ6D  gpMOLwl5zy               CB            1938
1   0Oq6lLZgM6  gpMOLwl5zy               ST            3605
2   2lqRJeA4qr  gpMOLwl5zy                W              12
3   2vQ1dVlLqr  gpMOLwl5zy               DM              32
4   2vQ1NO0OMr  gpMOLwl5zy                W            1876
5   315V7zn7q9  gpMOLwl5zy               CM             353
6   315VXPJEQ9  gpMOLwl5zy               CB            9784
7   4JMAaoa7MK  gpMOLwl5zy               FB            3047
8   4JMAolz1qK  gpMOLwl5zy               DM            8713
9   4wM4J8bNqj  gpMOLwl5zy                W            4729
10  7vQ7BardqD  gpMOLwl5zy               DM              57
11  7VqGjBpz5v  gpMOLwl5zy                W            1343
12  7VqGjPKj5v  gpMOLwl5zy               CB            2371
13  9vQ2dZE15K  gpMOLwl5zy               ST             449
14  9YqdogzE5v  gpMOLwl5zy                W            1624
15  BLMvzPNlMx  gpMOLwl5zy                W            2860
16  EGMPlpRxMa  gpMOLwl5zy               ST            2721
17  eV5DzmNmQK  gpMOLwl5zy               CB             864
18  eV5Dzr7EQK  gpMOLwl5zy                W             290
19  eVq3alzDMW  gpMOLwl5zy               FB              40
20  eVq3xk1VQW  gpMOLwl5zy               DM             752
21  gOMn66nAMw  gpMOLwl5zy               DM           10923
22  gOMnR6e6Mw  gpMOLwl5zy               FB            7873
23  gpMOaDWrqz  gpMOLwl5zy               CM            2415
24  gpMOz1KyQz  gpMOLwl5zy               ST            1653
25  gpMOzKV7Qz  gpMOLwl5zy                W             408
26  KXMekOprq6  gpMOLwl5zy               AM            9271
27  KXMeOaaPq6  gpMOLwl5zy                W            3710
28  ljqE2ekNQx  gpMOLwl5zy               FB            4642
29  ljqE2PwVQx  gpMOLwl5zy                W             293
30  ljqEjLaEQx  gpMOLwl5zy                W            7128
31  N6MmepZxME  gpMOLwl5zy               DM            3418
32  NPqxm7JXQ9  gpMOLwl5zy               FB              94
33  NWMWVR6jQl  gpMOLwl5zy               CB            1962
34  NWMWXylK5l  gpMOLwl5zy               CB            1123
35  Oa5wVLWAM1  gpMOLwl5zy               FB             995
36  Oa5wVojBM1  gpMOLwl5zy               DM              70
37  Oa5wVwxXM1  gpMOLwl5zy               FB             275
38  Oa5wVzD9M1  gpMOLwl5zy               CB             391
39  p6qb0L4M0G  gpMOLwl5zy               CB            3356
40  p6qbenoB50  gpMOLwl5zy                W            4918
41  raMyA6KRMd  gpMOLwl5zy               FB            9307
42  raMyAn8AMd  gpMOLwl5zy               CB            2885
43  wvq9bOBQWn  gpMOLwl5zy               DM             976
44  wvq9epE3qW  gpMOLwl5zy               ST             435
45  Xj5Y6AlAqb  gpMOLwl5zy               ST             246
46  Xj5Y9bmX5b  gpMOLwl5zy               ST            1413
47  Xj5Y9eBx5b  gpMOLwl5zy                W              62
48  xW5pynPBqg  gpMOLwl5zy               FB            1758
49  zeQZzPgQKw  gpMOLwl5zy               ST             809

                                                 data
0   [{'action_type': 'Dribbling', 'goals_added_raw...
1   [{'action_type': 'Dribbling', 'goals_added_raw...
2   [{'action_type': 'Dribbling', 'goals_added_raw...
3   [{'action_type': 'Dribbling', 'goals_added_raw...
4   [{'action_type': 'Dribbling', 'goals_added_raw...
5   [{'action_type': 'Dribbling', 'goals_added_raw...
6   [{'action_type': 'Dribbling', 'goals_added_raw...
7   [{'action_type': 'Dribbling', 'goals_added_raw...
8   [{'action_type': 'Dribbling', 'goals_added_raw...
9   [{'action_type': 'Dribbling', 'goals_added_raw...
10  [{'action_type': 'Dribbling', 'goals_added_raw...
11  [{'action_type': 'Dribbling', 'goals_added_raw...
12  [{'action_type': 'Dribbling', 'goals_added_raw...
13  [{'action_type': 'Dribbling', 'goals_added_raw...
14  [{'action_type': 'Dribbling', 'goals_added_raw...
15  [{'action_type': 'Dribbling', 'goals_added_raw...
16  [{'action_type': 'Dribbling', 'goals_added_raw...
17  [{'action_type': 'Dribbling', 'goals_added_raw...
18  [{'action_type': 'Dribbling', 'goals_added_raw...
19  [{'action_type': 'Dribbling', 'goals_added_raw...
20  [{'action_type': 'Dribbling', 'goals_added_raw...
21  [{'action_type': 'Dribbling', 'goals_added_raw...
22  [{'action_type': 'Dribbling', 'goals_added_raw...
23  [{'action_type': 'Dribbling', 'goals_added_raw...
24  [{'action_type': 'Dribbling', 'goals_added_raw...
25  [{'action_type': 'Dribbling', 'goals_added_raw...
26  [{'action_type': 'Dribbling', 'goals_added_raw...
27  [{'action_type': 'Dribbling', 'goals_added_raw...
28  [{'action_type': 'Dribbling', 'goals_added_raw...
29  [{'action_type': 'Dribbling', 'goals_added_raw...
30  [{'action_type': 'Dribbling', 'goals_added_raw...
31  [{'action_type': 'Dribbling', 'goals_added_raw...
32  [{'action_type': 'Dribbling', 'goals_added_raw...
33  [{'action_type': 'Dribbling', 'goals_added_raw...
34  [{'action_type': 'Dribbling', 'goals_added_raw...
35  [{'action_type': 'Dribbling', 'goals_added_raw...
36  [{'action_type': 'Dribbling', 'goals_added_raw...
37  [{'action_type': 'Dribbling', 'goals_added_raw...
38  [{'action_type': 'Dribbling', 'goals_added_raw...
39  [{'action_type': 'Dribbling', 'goals_added_raw...
40  [{'action_type': 'Dribbling', 'goals_added_raw...
41  [{'action_type': 'Dribbling', 'goals_added_raw...
42  [{'action_type': 'Dribbling', 'goals_added_raw...
43  [{'action_type': 'Dribbling', 'goals_added_raw...
44  [{'action_type': 'Dribbling', 'goals_added_raw...
45  [{'action_type': 'Dribbling', 'goals_added_raw...
46  [{'action_type': 'Dribbling', 'goals_added_raw...
47  [{'action_type': 'Dribbling', 'goals_added_raw...
48  [{'action_type': 'Dribbling', 'goals_added_raw...
49  [{'action_type': 'Dribbling', 'goals_added_raw...

In [13]:
austin_player_ids = austin_players_goals_added['player_id']
print(austin_player_ids)

0     0Oq67EgQ6D
1     0Oq6lLZgM6
2     2lqRJeA4qr
3     2vQ1dVlLqr
4     2vQ1NO0OMr
5     315V7zn7q9
6     315VXPJEQ9
7     4JMAaoa7MK
8     4JMAolz1qK
9     4wM4J8bNqj
10    7vQ7BardqD
11    7VqGjBpz5v
12    7VqGjPKj5v
13    9vQ2dZE15K
14    9YqdogzE5v
15    BLMvzPNlMx
16    EGMPlpRxMa
17    eV5DzmNmQK
18    eV5Dzr7EQK
19    eVq3alzDMW
20    eVq3xk1VQW
21    gOMn66nAMw
22    gOMnR6e6Mw
23    gpMOaDWrqz
24    gpMOz1KyQz
25    gpMOzKV7Qz
26    KXMekOprq6
27    KXMeOaaPq6
28    ljqE2ekNQx
29    ljqE2PwVQx
30    ljqEjLaEQx
31    N6MmepZxME
32    NPqxm7JXQ9
33    NWMWVR6jQl
34    NWMWXylK5l
35    Oa5wVLWAM1
36    Oa5wVojBM1
37    Oa5wVwxXM1
38    Oa5wVzD9M1
39    p6qb0L4M0G
40    p6qbenoB50
41    raMyA6KRMd
42    raMyAn8AMd
43    wvq9bOBQWn
44    wvq9epE3qW
45    Xj5Y6AlAqb
46    Xj5Y9bmX5b
47    Xj5Y9eBx5b
48    xW5pynPBqg
49    zeQZzPgQKw
Name: player_id, dtype: object

In [14]:
# Loop through each player ID to fetch data
for current_id in austin_player_ids:
    # Fetch player data
    player_data = asa_client.get_players(ids=current_id)
    print(player_data['player_id'], player_data['player_name'])

918    0Oq67EgQ6D
Name: player_id, dtype: object 918    Matt Besler
Name: player_name, dtype: object
941    0Oq6lLZgM6
Name: player_id, dtype: object 941    Maximiliano Urruti
Name: player_name, dtype: object
1076    2lqRJeA4qr
8858    2lqRJeA4qr
Name: player_id, dtype: object 1076    Bryant Farkarlun
8858    Bryant Farkarlun
Name: player_name, dtype: object
1166    2vQ1dVlLqr
8921    2vQ1dVlLqr
Name: player_id, dtype: object 1166    Alonso Jiménez
8921    Alonso Jiménez
Name: player_name, dtype: object
1193    2vQ1NO0OMr
Name: player_id, dtype: object 1193    Jáder Obrian
Name: player_name, dtype: object
1205    315V7zn7q9
4203    315V7zn7q9
Name: player_id, dtype: object 1205    Sofiane Djeffal
4203    Sofiane Djeffal
Name: player_name, dtype: object
1253    315VXPJEQ9
4263    315VXPJEQ9
Name: player_id, dtype: object 1253    Julio Cascante
4263    Julio Cascante
Name: player_name, dtype: object
1286    4JMAaoa7MK
Name: player_id, dtype: object 1286    Héctor Jiménez
Name: player_name, dtype: object
1307    4JMAolz1qK
Name: player_id, dtype: object 1307    Daniel Pereira Gil
Name: player_name, dtype: object
1354    4wM4J8bNqj
4383    4wM4J8bNqj
Name: player_id, dtype: object 1354    Owen Wolff
4383    Owen Wolff
Name: player_name, dtype: object
1396    7vQ7BardqD
4432    7vQ7BardqD
Name: player_id, dtype: object 1396    Frederik Kleemann
4432    Frederik Kleemann
Name: player_name, dtype: object
1489    7VqGjBpz5v
4520    7VqGjBpz5v
Name: player_id, dtype: object 1489    Jared Stroud
4520    Jared Stroud
Name: player_name, dtype: object
1498    7VqGjPKj5v
Name: player_id, dtype: object 1498    Jhohan Romaña
Name: player_name, dtype: object
1570    9vQ2dZE15K
4607    9vQ2dZE15K
Name: player_id, dtype: object 1570    Will Bruin
4607    Will Bruin
Name: player_name, dtype: object
1634    9YqdogzE5v
Name: player_id, dtype: object 1634    Rodney Redes
Name: player_name, dtype: object
1884    BLMvzPNlMx
Name: player_id, dtype: object 1884    Cecilio Domínguez
Name: player_name, dtype: object
1950    EGMPlpRxMa
9436    EGMPlpRxMa
Name: player_id, dtype: object 1950    Gyasi Zardes
9436    Gyasi Zardes
Name: player_name, dtype: object
2054    eV5DzmNmQK
9517    eV5DzmNmQK
Name: player_id, dtype: object 2054    Kipp Keller
9517    Kipp Keller
Name: player_name, dtype: object
2055    eV5Dzr7EQK
5176    eV5Dzr7EQK
9520    eV5Dzr7EQK
Name: player_id, dtype: object 2055    Calvin Fodrey
5176    Calvin Fodrey
9520    Calvin Fodrey
Name: player_name, dtype: object
2069    eVq3alzDMW
Name: player_id, dtype: object 2069    Mikkel Desler
Name: player_name, dtype: object
2125    eVq3xk1VQW
9544    eVq3xk1VQW
Name: player_id, dtype: object 2125    Sebastian Berhalter
9544    Sebastian Berhalter
Name: player_name, dtype: object
2208    gOMn66nAMw
Name: player_id, dtype: object 2208    Alexander Ring
Name: player_name, dtype: object
2271    gOMnR6e6Mw
Name: player_id, dtype: object 2271    Nick Lima
Name: player_name, dtype: object
2311    gpMOaDWrqz
Name: player_id, dtype: object 2311    Tomás Pochettino
Name: player_name, dtype: object
2367    gpMOz1KyQz
5538    gpMOz1KyQz
9722    gpMOz1KyQz
Name: player_id, dtype: object 2367    Diego Rubio
5538    Diego Rubio
9722    Diego Rubio
Name: player_name, dtype: object
2379    gpMOzKV7Qz
Name: player_id, dtype: object 2379    Kekuta Manneh
Name: player_name, dtype: object
2736    KXMekOprq6
Name: player_id, dtype: object 2736    Sebastián Driussi
Name: player_name, dtype: object
2746    KXMeOaaPq6
Name: player_id, dtype: object 2746    Emiliano Rigoni
Name: player_name, dtype: object
2763    ljqE2ekNQx
Name: player_id, dtype: object 2763    Zan Kolmanic
Name: player_name, dtype: object
2770    ljqE2PwVQx
5960    ljqE2PwVQx
Name: player_id, dtype: object 2770    Memo Rodríguez
5960    Memo Rodríguez
Name: player_name, dtype: object
2787    ljqEjLaEQx
Name: player_id, dtype: object 2787    Diego Fagundez
Name: player_name, dtype: object
2847    N6MmepZxME
Name: player_id, dtype: object 2847    Jhojan Valencia
Name: player_name, dtype: object
2901    NPqxm7JXQ9
8579    NPqxm7JXQ9
Name: player_id, dtype: object 2901    Ben Sweat
8579    Ben Sweat
Name: player_name, dtype: object
2980    NWMWVR6jQl
Name: player_id, dtype: object 2980    Brendan Hines-Ike
Name: player_name, dtype: object
2997    NWMWXylK5l
Name: player_id, dtype: object 2997    Matt Hedges
Name: player_name, dtype: object
3050    Oa5wVLWAM1
6338    Oa5wVLWAM1
Name: player_id, dtype: object 3050    Adam Lundkvist
6338    Adam Lundkvist
Name: player_name, dtype: object
3052    Oa5wVojBM1
Name: player_id, dtype: object 3052    Washington Corozo
Name: player_name, dtype: object
3055    Oa5wVwxXM1
6348    Oa5wVwxXM1
Name: player_id, dtype: object 3055    Aedan Stanley
6348    Aedan Stanley
Name: player_name, dtype: object
3060    Oa5wVzD9M1
Name: player_id, dtype: object 3060    Aleksandar Radovanovic
Name: player_name, dtype: object
3205    p6qb0L4M0G
Name: player_id, dtype: object 3205    Ruben Gabrielsen
Name: player_name, dtype: object
3222    p6qbenoB50
Name: player_id, dtype: object 3222    Ethan Finlay
Name: player_name, dtype: object
3341    raMyA6KRMd
6610    raMyA6KRMd
Name: player_id, dtype: object 3341    Jon Gallagher
6610    Jon Gallagher
Name: player_name, dtype: object
3344    raMyAn8AMd
Name: player_id, dtype: object 3344    Leo Väisänen
Name: player_name, dtype: object
3552     wvq9bOBQWn
10520    wvq9bOBQWn
Name: player_id, dtype: object 3552     Felipe
10520    Felipe
Name: player_name, dtype: object
3561    wvq9epE3qW
6860    wvq9epE3qW
Name: player_id, dtype: object 3561    Manny Perez
6860    Manny Perez
Name: player_name, dtype: object
3612     Xj5Y6AlAqb
10587    Xj5Y6AlAqb
Name: player_id, dtype: object 3612     Orrin McKinze Gaines II
10587    Orrin McKinze Gaines II
Name: player_name, dtype: object
3644    Xj5Y9bmX5b
Name: player_id, dtype: object 3644    Moussa Djitté
Name: player_name, dtype: object
3645    Xj5Y9eBx5b
Name: player_id, dtype: object 3645    Osman Bukari
Name: player_name, dtype: object
3789    xW5pynPBqg
Name: player_id, dtype: object 3789    Guilherme Biro
Name: player_name, dtype: object
3855    zeQZzPgQKw
Name: player_id, dtype: object 3855    Danny Hoesen
Name: player_name, dtype: object

Mikkel Desler - eVq3alzDMW
Owen Wolff - 4wM4J8bNqj

In [16]:
Ga = asa_client.get_player_goals_added(player_ids='2vQ1NO0OMr')
print(Ga)

    player_id                   team_id general_position  minutes_played  \
0  2vQ1NO0OMr  [gpMOLwl5zy, mKAqBBmqbg]                W            8028

                                                data
0  [{'action_type': 'Dribbling', 'goals_added_raw...

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itscalledsoccer/client.py:303: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  resp_df = read_json(json.dumps(response.json()))